# Item configuration script
# Script generated by LED: Mar 25 1999 11:31:05


# Script with 100 Items.

o=Bladex.CreateEntity("NoName0","Antorcha2",297361.835000,-4071.372000,-195912.478000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.504344,0.504344,-0.495618,0.495618
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.500000,(240,126,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","CandilAurelio",329375.034000,-9578.297000,-209772.180000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.030844,0.030844,-0.706434,0.706434
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.538033,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName14","CandilAurelio",344473.054000,-2127.077000,-159284.689000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.696364,0.696364,-0.122788,0.122788
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.764935,0.341290,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName17","CandilAurelio",331370.120000,-2157.140000,-170357.378000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.512917,0.512917,0.486740,-0.486740
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.653295,0.294820,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName65","CandilAurelio",331882.088000,13042.139000,-202212.882000)
o.Static=1
o.Scale=1.030301
o.Orientation=1.000000,0.000000,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.003181,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName70","CandilAurelio",377605.291000,-1466.285000,-208822.431000)
o.Static=1
o.Scale=1.347849
o.Orientation=0.500000,0.500000,0.500000,-0.500000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.000000,0.300000,(240,126,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName71","CandilAurelio",358009.985000,19587.297000,-201361.379000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.039976,0.480230,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName72","CandilAurelio",354554.323000,25523.232000,-210878.343000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 3 ]
o.Lights=[ (14.635594,0.457362,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName73","CandilAurelio",333741.591000,21716.900000,-231533.696000)
o.Static=1
o.Scale=1.000000
o.Orientation=1.000000,0.000000,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (12.642778,0.341288,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","LamparaAurelio",348806.032000,-2710.393000,-245188.907000)
o.Static=1
o.Scale=2.871214
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (40.000000,0.500000,(227,119,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",290307.028000,6662.525000,-183758.632000)
o.Static=1
o.Scale=1.061520
o.Orientation=0.495618,0.495618,0.504344,-0.504344
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.031250,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha2",307252.397000,-3110.175000,-188562.472000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.477714,0.477714,-0.521334,0.521334
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(255,134,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorchaenpared",311418.325000,1656.454000,-177650.290000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.018510,0.018510,-0.706864,0.706864
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Antorcha2",312151.771000,-3267.138000,-201589.633000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.541675,0.541675,0.454519,-0.454519
o.FiresIntensity=[ 0 ]
o.Lights=[ (8.000000,0.100000,(234,123,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Tinaja",311418.024000,-133.392000,-201215.016000)
o.Static=1
o.Scale=1.474123
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Tinaja",311183.350000,223.783000,-200012.120000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Tinaja",311142.408000,-43.692000,-202612.335000)
o.Static=1
o.Scale=1.361327
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Tinaja",310081.028000,-29.060000,-201652.903000)
o.Static=1
o.Scale=1.334504
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Tinaja",309738.265000,543.164000,-199616.913000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.791185,0.273190,-0.388448,-0.385359
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",295126.556000,-2574.565000,-191226.813000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.500000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha2",295128.815000,-2650.218000,-200858.441000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.012342,0.012341,-0.706999,0.706999
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.500000,(232,121,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",348773.949000,5966.724000,-236923.197000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.037007,0.037007,0.706138,-0.706138
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(215,113,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","CandilAurelio",361746.925000,17875.814000,-216972.801000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.030844,0.030844,0.706434,-0.706434
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","CandilAurelio",383115.694000,18915.764000,-215817.289000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.491198,0.491198,-0.508650,0.508650
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(225,118,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","CandilAurelio",384519.865000,18479.676000,-239096.102000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(225,118,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorcha2",391116.522000,7693.329000,-210714.397000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(223,117,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorcha2",400770.482000,8417.946000,-220584.587000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.504344,0.504344,0.495618,-0.495618
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(230,120,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Antorcha2",389490.167000,12607.808000,-211998.870000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(217,114,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",400769.718000,15786.737000,-216601.227000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(221,116,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha2",393897.169000,17764.764000,-224074.902000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(240,126,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",300527.689000,6874.434000,-188459.711000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.512915,0.512917,-0.486740,0.486743
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorchaenpared",293925.603000,6948.196000,-192547.165000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Antorchaenpared",287696.571000,6666.776000,-201934.726000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707080,0.707080,-0.006171,0.006171
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.300000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Antorchaenpared",301768.052000,2632.017000,-173837.170000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorcha2",344885.590000,14050.000000,-233270.891000)
o.Static=1
o.Scale=1.010000
o.Orientation=0.521334,0.521334,0.477715,-0.477715
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(255,128,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",359883.114000,12482.870000,-232010.115000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,0.500000,-0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(255,128,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",341362.813000,13590.206000,-203060.179000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.508650,0.508650,-0.491198,0.491198
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(249,131,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",321547.360000,7729.327000,-214045.377000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.674380,0.674380,-0.212631,0.212631
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.500000,(255,138,9)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",342262.494000,12756.175000,-218974.857000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.468543,0.468543,0.529591,-0.529591
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(234,123,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Reja",325996.404000,1552.701000,-208810.410000)
o.Static=1
o.Scale=1.694466
o.Orientation=0.000000,1.000000,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","LamparaAurelio",336063.398000,8507.391000,-196708.936000)
o.Static=1
o.Scale=0.734577
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(255,136,4)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",328513.243000,5869.767000,-226617.538000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,-0.000000,-0.000007
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.300000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",339201.786000,13627.071000,-192881.006000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.696364,0.696364,-0.122788,0.122788
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.100000,(185,97,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorcha2",334885.926000,-2686.561000,-182121.286000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,0.500000,-0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Antorcha2",316364.919000,-3364.284000,-182355.321000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(217,114,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",337059.315000,-993.903000,-160163.561000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.270598,0.270598,-0.653282,0.653282
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(223,117,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",312866.303000,-1386.760000,-162063.050000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.627211,0.627211,-0.326506,0.326506
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(230,120,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",332837.137000,-8570.485000,-159315.011000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.596368,0.596368,0.379928,-0.379928
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(213,112,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Rastrillo",336414.765000,-7279.499000,-156575.738000)
o.Static=1
o.Scale=0.779768
o.Orientation=0.706131,0.708076,0.002189,-0.001632
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",321313.792000,-3421.066000,-175398.218000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.683013,0.683013,-0.183013,0.183013
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.400000,(240,126,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",340601.612000,12788.225000,-107650.157000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.504345,0.504345,0.495617,-0.495617
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",356128.514000,2167.660000,-137702.443000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.200829,0.200829,-0.677988,0.677988
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(251,132,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",347950.627000,-136.189000,-151250.418000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.300000,(223,117,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",338481.562000,12876.317000,-137607.203000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.655618,0.655618,-0.264887,0.264887
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.030000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",343259.789000,-2825.265000,-132831.544000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.298836,0.298836,0.640856,-0.640857
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",307019.086000,20557.744000,-84234.782000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.430459,0.430459,0.560986,-0.560986
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",284693.567000,23843.692000,-85306.783000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.512917,0.512917,0.486740,-0.486740
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Antorchaenpared",282124.525000,28294.343000,-102357.998000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.579228,0.579228,-0.405580,0.405580
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",324926.608000,18798.307000,-98305.787000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.504345,0.504344,-0.495617,0.495617
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",295116.548000,34165.246000,-104667.412000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.553388,0.553388,-0.440184,0.440184
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",311609.834000,35060.205000,-103635.857000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.030844,0.030843,0.706434,-0.706434
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",329382.765000,42386.452000,-125374.789000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.030844,0.030844,-0.706434,0.706434
o.FiresIntensity=[ 0 ]
o.Lights=[ (20.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",361185.383000,6892.040000,-112497.120000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 0 ]
o.Lights=[ (45.000000,0.400000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",323171.296000,42235.649000,-94115.165000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.700909,0.713250,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Rastrillo",324994.572000,42308.979000,-100597.985000)
o.Static=1
o.Scale=0.932718
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",325014.078000,11531.207000,-123401.358000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",324985.055000,25739.254000,-99040.025000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",314056.242000,42623.049000,-91592.054000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.541675,0.541675,-0.454519,0.454519
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",332436.829000,-1988.230000,-88157.258000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.463904,0.463904,-0.533660,0.533661
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",327147.611000,26660.575000,-82106.818000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,0.500000,-0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Antorchaenpared",324865.279000,-2540.444000,-81748.735000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.542837,0.517067,-0.470146,0.465760
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",334249.051000,-224.101000,-78078.032000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.706999,0.706999,-0.012340,0.012340
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Antorchaenpared",317545.795000,-2959.518000,-88229.204000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.517145,0.517145,-0.482246,0.482246
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",315723.448000,-757.566000,-78835.058000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.012342,0.012341,-0.706999,0.706999
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",334316.999000,-762.025000,-56899.441000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",315727.811000,-71.697000,-56788.532000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Lamparaegipto",318421.288000,13512.526000,-51669.632000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.700909,0.713250,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (75.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Lamparaegipto",331258.582000,13569.458000,-62069.006000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.700909,0.713250,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (75.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",353517.850000,3660.465000,-59130.257000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.486740,0.486740,-0.512917,0.512917
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",352299.818000,7353.077000,-45079.781000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.662941,0.669952,0.224169,-0.247834
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",343327.080000,10090.741000,-41930.807000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.508650,0.508650,-0.491198,0.491198
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",295886.013000,3462.533000,-59142.471000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.541675,0.541675,-0.454519,0.454519
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.300000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",297727.341000,7451.682000,-45131.457000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.188966,0.188966,0.681390,-0.681390
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Antorchaenpared",305577.674000,10534.577000,-41949.479000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.508650,0.508650,-0.491198,0.491198
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha2",321870.175000,10799.104000,-34553.086000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Lamparaegipto",312084.222000,17794.011000,-3366.281000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Lamparaegipto",337382.895000,17797.056000,-3514.067000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorcha2",331615.177000,30134.238000,-3244.948000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.517450,0.499695,-0.482550,0.499695
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorcha2",318315.448000,30198.172000,-3264.590000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.477714,0.477714,0.521334,-0.521334
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",324892.635000,34626.446000,3254.711000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 0 ]
o.Lights=[ (25.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorchaenpared",323413.428000,13533.522000,26120.708000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.706434,0.706434,0.030844,-0.030844
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",323419.599000,34532.712000,26278.848000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.696364,0.696364,-0.122788,0.122788
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorchaenpared",345018.995000,35629.744000,36131.568000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.012342,0.012341,-0.706999,0.706999
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.100000,(128,64,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Lamparaegipto",467556.693000,45993.834000,86380.805000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.700909,0.713250,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.500000,(111,58,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Lamparaegipto",467528.435000,45995.987000,36020.362000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.700909,0.713250,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.500000,(111,58,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Lamparaegipto",479582.276000,45997.844000,61238.712000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.300000,(111,58,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",352247.489000,13896.763000,-243924.167000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (15.000000,0.100000,(240,120,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",322418.596000,6490.217000,-232741.502000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha2",340886.871000,-3755.236000,-205268.089000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.012342,0.012341,0.706999,-0.706999
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.500000,(236,124,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha2",327650.178487,-1805.259648,-228358.183827)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.500000,(185,97,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


