# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 2 Items.

o=Bladex.CreateEntity("PuertaFin0","PuertaFernando",90551.818845,-11871.737814,195045.357000)
o.Scale=1.000000
o.Orientation=0.533660,0.533660,0.463904,-0.463904
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("PuertaFin1","PuertaFernando",98230.671460,-11913.530670,195087.409000)
o.Scale=1.000000
o.Orientation=0.454519,0.454519,0.541675,-0.541675
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


