import LoadBar
LoadBar.LanguageProgressBar(364,"Blade_progress.jpg")

#BBLib.GetnOpenedInputFiles()

import Bladex

execfile("../../Scripts/sys_init.py")

Bladex.ReadLevel("dwarf.lvl")

execfile("../../Scripts/BladeInit.py")


# Item configuration script
# Script generated by LED: Aug  5 1998 19:56:40


execfile("DefFuncs.py")
execfile("MusicEvents.py")
execfile("TextureMaterials.py")
execfile("Musica.py")

import Reference

if Reference.PYTHON_DEBUG >= 1:
	execfile("Positions.py")

execfile ("sol.py")
execfile ("agua.py")
execfile("chorritos.py")
execfile("cascadapint.py")
execfile("burning.py")
execfile("FinalScene.py")
execfile("EscenaOrk.py")

execfile ("Sonidos.py")
execfile ("Sonidospuntuales.py")

execfile ("Puertdw.py")
execfile ("Puertatrampa1.py")
execfile ("elevator.py")

execfile ("Escalera.py")
execfile ("Combinacion_Pulsadores.py")
execfile ("DERR.py")


execfile("luces.py")
execfile("pira1.py")
execfile("hogueras.py")


execfile ("objs.py")
execfile ("rejas.py")
execfile ("biblio.py")
execfile ("libros.py")
execfile ("objrot.py")
execfile ("armas.py")
execfile ("telas.py")
execfile("bloqueo.py")

execfile ("Enemigos.py")
execfile ("comestibles.py")
execfile ("pocimas.py")

execfile ("flechas_yo.py")
execfile ("Cuchillas.py")

execfile ("temblores.py")
execfile ("enanos.py")

execfile ("InicioScene.py")

#Bladex.SetCallCheck(1)		#no descomentar
