import Sparks

Sparks.SetMetalSparkling("drastrillo1")


Sparks.SetMetalSparkling("dcandelabro1")
Sparks.SetMetalSparkling("dcandelabro2")
Sparks.SetMetalSparkling("dcandelabro3")
Sparks.SetMetalSparkling("dcandelabro4")

Sparks.SetMetalSparkling("dcandelabro6")
Sparks.SetMetalSparkling("dcandelabro7")

Sparks.SetMetalSparkling("metalo1")
Sparks.SetMetalSparkling("metalo2")
Sparks.SetMetalSparkling("metalo3")
Sparks.SetMetalSparkling("metalo4")
Sparks.SetMetalSparkling("metalo5")
Sparks.SetMetalSparkling("metalo6")
Sparks.SetMetalSparkling("metalo7")
Sparks.SetMetalSparkling("metalo8")
Sparks.SetMetalSparkling("metalo9")
Sparks.SetMetalSparkling("metalo10")
Sparks.SetMetalSparkling("metalo11")
Sparks.SetMetalSparkling("metalo12")
Sparks.SetMetalSparkling("metalo13")
Sparks.SetMetalSparkling("metalo14")
Sparks.SetMetalSparkling("metalo15")
Sparks.SetMetalSparkling("metalo16")
Sparks.SetMetalSparkling("metalo17")
Sparks.SetMetalSparkling("metalo18")
Sparks.SetMetalSparkling("metalo19")
Sparks.SetMetalSparkling("metalo20")
Sparks.SetMetalSparkling("metalo21")
#Sparks.SetMetalSparkling("metalo22")
#Sparks.SetMetalSparkling("metalo23")
#Sparks.SetMetalSparkling("metalo24")
#Sparks.SetMetalSparkling("metalo25")
#Sparks.SetMetalSparkling("metalo26")
#Sparks.SetMetalSparkling("metalo27")
#Sparks.SetMetalSparkling("metalo28")
#Sparks.SetMetalSparkling("metalo29")



Sparks.SetWoodenSparkling("mesafinal")

Sparks.SetWoodenSparkling("madero1")
Sparks.SetWoodenSparkling("madero2")
Sparks.SetWoodenSparkling("madero3")
Sparks.SetWoodenSparkling("madero4")
Sparks.SetWoodenSparkling("madero5")
Sparks.SetWoodenSparkling("madero6")
Sparks.SetWoodenSparkling("madero7")
Sparks.SetWoodenSparkling("madero8")
Sparks.SetWoodenSparkling("madero9")
Sparks.SetWoodenSparkling("madero10")
Sparks.SetWoodenSparkling("madero11")
Sparks.SetWoodenSparkling("madero12")
Sparks.SetWoodenSparkling("madero13")
Sparks.SetWoodenSparkling("madero14")
Sparks.SetWoodenSparkling("madero15")
Sparks.SetWoodenSparkling("madero16")
Sparks.SetWoodenSparkling("madero17")
Sparks.SetWoodenSparkling("madero18")
Sparks.SetWoodenSparkling("madero19")
Sparks.SetWoodenSparkling("madero20")






Sparks.SetStoneSparkling("pedrolo1")
Sparks.SetStoneSparkling("pedrolo2")
Sparks.SetStoneSparkling("pedrolo3")
Sparks.SetStoneSparkling("pedrolo4")
Sparks.SetStoneSparkling("pedrolo5")
Sparks.SetStoneSparkling("pedrolo6")
Sparks.SetStoneSparkling("pedrolo7")
Sparks.SetStoneSparkling("pedrolo8")
Sparks.SetStoneSparkling("pedrolo9")
Sparks.SetStoneSparkling("pedrolo10")
Sparks.SetStoneSparkling("pedrolo11")
Sparks.SetStoneSparkling("pedrolo12")
Sparks.SetStoneSparkling("pedrolo13")
Sparks.SetStoneSparkling("pedrolo14")
Sparks.SetStoneSparkling("pedrolo15")
Sparks.SetStoneSparkling("pedrolo16")
Sparks.SetStoneSparkling("pedrolo17")
Sparks.SetStoneSparkling("pedrolo18")
Sparks.SetStoneSparkling("pedrolo19")
Sparks.SetStoneSparkling("pedrolo20")
Sparks.SetStoneSparkling("pedrolo21")
Sparks.SetStoneSparkling("pedrolo22")
Sparks.SetStoneSparkling("pedrolo23")
#Sparks.SetStoneSparkling("pedrolo24")
Sparks.SetStoneSparkling("pedrolo25")