import Reference
import MenuText

# Item configuration script
# Script generated by LED: Oct  5 1999 12:37:44


# Script with 127 Objects and 0 Entities.

o=Bladex.CreateEntity("NoName0","Roca1Aurelio",193860.552000,4232.060000,74076.493000)
o.Static=0
o.Scale=3.468740
o.Orientation=0.026177,0.999657,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Antorchaenpared",233558.385000,-6431.819000,116608.649000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.326506,0.440184,-0.627211,0.553388
o.FiresIntensity=[ 0 ]
o.Lights=[ (30.000000,0.312500,(242,128,0)) ]


o=Bladex.CreateEntity("NoName0","Roca1Aurelio",217397.890000,493.234000,111976.320000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.992546,-0.121869,0.000000,0.000000


o=Bladex.CreateEntity("NoName1","Roca1Aurelio",219364.564000,-285.656000,107114.205000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.998135,-0.061049,0.000000,0.000000


o=Bladex.CreateEntity("NoName2","Roca1Aurelio",227157.384000,-372.940000,111494.571000)
o.Static=0
o.Scale=1.564811
o.Orientation=0.461239,-0.815238,-0.245464,-0.249786


o=Bladex.CreateEntity("NoName3","Roca1Aurelio",222174.194000,-5.866000,116268.772000)
o.Static=0
o.Scale=1.126825
o.Orientation=0.270266,0.393239,-0.497768,0.724256


o=Bladex.CreateEntity("NoName4","Piedra_01",220998.647000,-353.071000,112069.754000)
o.Static=0
o.Scale=0.712973
o.Orientation=0.663449,-0.274708,-0.695829,-0.013913


o=Bladex.CreateEntity("NoName5","Piedra_01",221753.603000,-381.990000,111525.178000)
o.Static=0
o.Scale=0.803396
o.Orientation=0.963267,0.029422,0.247877,0.099038


o=Bladex.CreateEntity("NoName6","Piedra_01",226169.922000,-593.229000,114760.505000)
o.Static=0
o.Scale=0.932718
o.Orientation=0.990303,-0.044569,0.027590,0.128656


o=Bladex.CreateEntity("NoName7","Restos",223573.469000,-628.163000,115864.920000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName8","Roca1Aurelio",214190.295000,2315.570000,103387.702000)
o.Static=0
o.Scale=1.518790
o.Orientation=0.704416,0.704416,0.061628,-0.061628


o=Bladex.CreateEntity("NoName9","Roca1Aurelio",225751.564000,-2896.714000,119794.071000)
o.Static=0
o.Scale=2.173037
o.Orientation=0.622152,-0.297765,0.719475,-0.081354


o=Bladex.CreateEntity("NoName10","Piedra_01",186271.618000,6661.576000,75233.295000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.981805,-0.079142,0.083809,0.150904


o=Bladex.CreateEntity("NoName11","Piedra_01",184304.617000,6662.244000,74385.336000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.982158,-0.094450,-0.097954,0.129806


o=Bladex.CreateEntity("NoName1","Roca1Aurelio",230579.253000,-4899.910000,114281.582000)
o.Static=0
o.Scale=1.580459
o.Orientation=0.998135,0.061049,0.000000,0.000000


o=Bladex.CreateEntity("NoName2","Roca1Aurelio",243375.515000,-9947.340000,122689.047000)
o.Static=0
o.Scale=2.173037
o.Orientation=0.819152,-0.573576,0.000000,0.000000


o=Bladex.CreateEntity("ap1","Antorchaenpared",255365.718000,-645.987000,136798.713000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.482246,0.342812,0.517145,-0.618450
o.FiresIntensity=[ 0 ]
o.Lights=[ (20.000000,0.712500,(232,121,0)) ]


o=Bladex.CreateEntity("NoName4","Roca1Aurelio",244223.581000,-4602.927000,131584.189000)
o.Static=0
o.Scale=2.194768
o.Orientation=0.078459,0.996917,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Roca1Aurelio",249738.463000,-19319.720000,162811.208000)
o.Static=0
o.Scale=5.704800
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("ap2","Antorchaenpared",298084.087000,-573.383000,130636.377000)
o.Static=0
o.Scale=1.160969
o.Orientation=0.533660,0.463904,0.463904,-0.533660
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.700000,(236,124,0)) ]


o=Bladex.CreateEntity("kaja1","Caja_i_i",301085.663000,-280.709000,129083.845000)
o.Static=1
o.Scale=3.017675
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("kaja2","Caja_i_i",300285.202000,171.109000,126034.423000)
o.Static=1
o.Scale=1.947745
o.Orientation=0.677456,0.677314,0.202588,-0.203119
o.ExclusionMask=2


o=Bladex.CreateEntity("kaja3","Caja_i_i",300431.435000,-2109.505000,128535.928000)
o.Static=1
o.Scale=2.306723
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("cir1","Caja_i_r",300721.268000,-1429.460000,126016.344000)
o.Static=0
o.Scale=1.780901
o.Orientation=0.705117,0.704596,0.055942,-0.056787
o.ExclusionMask=2

o=Bladex.CreateEntity("a1","Antorcha",296165.107000,678.952000,129433.068000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.020496,0.997884,0.060848,-0.010263
o.FiresIntensity=[ 33 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName0","Tabla_xl",301648.088000,952.393000,124967.206000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.624338,0.624338,0.331967,-0.331967


o=Bladex.CreateEntity("NoName1","Tabla_xl",292145.478000,692.177000,125595.678000)
o.Static=0
o.Scale=1.445076
o.Orientation=0.534226,0.531025,0.466661,-0.463511


o=Bladex.CreateEntity("NoName2","Tabla_rota",292646.758000,693.475000,127670.320000)
o.Static=0
o.Scale=1.518790
o.Orientation=0.633095,0.633148,0.314890,-0.314893


o=Bladex.CreateEntity("NoName3","Tabla_rota",301463.223000,-242.786000,132982.738000)
o.Static=0
o.Scale=1.661078
o.Orientation=0.199286,-0.612363,-0.676329,0.357597


o=Bladex.CreateEntity("NoName1","Lamparatecho",332299.893000,-9496.327000,123230.244000)
o.Static=0
o.Scale=1.745810
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (22.000000,0.131250,(255,136,4)) ]


o=Bladex.CreateEntity("NoName0","Antorchaenpared",315144.456000,-708.362000,131167.503000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.606109,0.463904,0.364187,-0.533660
o.FiresIntensity=[ 0 ]
o.Lights=[ (7.000000,0.371250,(255,128,0)) ]


o=Bladex.CreateEntity("NoName0","Meson",324920.291000,-5619.847000,118555.303000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barcoc1","Barril",329966.224000,-5763.262000,130220.424000)
o.Static=0
o.Scale=1.816697
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barcoc2","Barril",331698.138000,-6085.112000,130333.427000)
o.Static=0
o.Scale=2.599273
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barcoc3","Barril",333701.271000,-5928.101000,129784.948000)
o.Static=0
o.Scale=2.216715
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barcoc4","Barril",332582.869000,-5942.747000,128435.346000)
o.Static=0
o.Scale=2.261271
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName5","Caliz",325205.820000,-6147.478000,117635.174000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName6","Caliz",324986.637000,-6146.522000,116935.391000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName10","Palangana",325033.693000,-6199.061000,120204.440000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 55 ]
o.Lights=[ (0.000000,0.031250,(0,0,0)) ]


o=Bladex.CreateEntity("NoName16","Cazo",324465.663000,-6127.576000,118640.839000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.984478,0.150788,0.066349,0.060534


o=Bladex.CreateEntity("NoName17","Cirio",324321.427000,-6354.032000,116794.604000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (1.000000,0.512500,(215,113,0)) ]


tab1=Bladex.CreateEntity("Taburete1","Taburete",322787.088000,-5338.100000,119228.334000)
tab1.Static=0
tab1.Scale=1.000000
tab1.Orientation=0.707107,0.707107,0.000000,0.000000
Reference.EntitiesSelectionData[tab1.Name]=(6.0,4000.0,MenuText.GetMenuText("Stool"))


tab2=Bladex.CreateEntity("Taburete2","Taburete",328161.349, -5336.24, 121469.378)
tab2.Static=0
tab2.Scale=1.000000
tab2.Orientation=0.707107,0.707107,0.000000,0.000000
Reference.EntitiesSelectionData[tab2.Name]=(6.0,4000.0,MenuText.GetMenuText("Stool"))


o=Bladex.CreateEntity("NoName0","Hoguera",334579.748000,-5279.980000,109773.413000)
o.Static=0
o.Scale=1.257163
o.Orientation=0.693293,0.712736,-0.041434,0.098156
o.FiresIntensity=[ 0 ]
o.Lights=[ (20.000000,0.512500,(240,126,0)) ]


o=Bladex.CreateEntity("NoName1","Hoguera",334176.701000,-5267.356000,109790.732000)
o.Static=0
o.Scale=1.459527
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 2 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName2","Hoguera",335060.914000,-5123.633000,109911.795000)
o.Static=0
o.Scale=1.518790
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ -3 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName3","Tronco",334407.099000,-5181.242000,110913.956000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.578671,0.107420,-0.493164,-0.640617


o=Bladex.CreateEntity("NoName0","Tronco",333461.186000,-5163.413000,110620.339000)
o.Static=0
o.Scale=1.104622
o.Orientation=0.621418,0.621418,-0.337402,0.337402


o=Bladex.CreateEntity("NoName1","Tronco",333691.647000,-5249.496000,110061.268000)
o.Static=0
o.Scale=1.160969
o.Orientation=0.654875,0.406878,0.071989,-0.632777


o=Bladex.CreateEntity("NoName2","Tronco",333886.541000,-5153.645000,109399.554000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.694115,0.694115,0.134922,-0.134922




o=Bladex.CreateEntity("NoName8","Cajon2",337133.112000,-8205.637000,120653.520000)
o.Static=0
o.Scale=0.844377
o.Orientation=0.491198,0.491198,0.508650,-0.508650


o=Bladex.CreateEntity("NoName9","Cajon2",337135.024000,-8142.663000,118987.723000)
o.Static=0
o.Scale=0.727304
o.Orientation=0.495618,0.495618,0.504344,-0.504344



o=Bladex.CreateEntity("NoName0","Skull",337263.615000,-6098.560000,116652.983000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.574476,0.418439,0.402317,0.577085


o=Bladex.CreateEntity("NoName1","Skull",337251.369000,-6097.669000,116068.522000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.576092,0.170282,0.675461,-0.427637


o=Bladex.CreateEntity("NoName2","Skull",337089.216000,-6099.333000,116316.531000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.730717,-0.080730,0.294072,-0.610784


o=Bladex.CreateEntity("NoName3","Skull",337429.875000,-6105.918000,117477.580000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.307521,0.638889,0.605003,0.362248


o=Bladex.CreateEntity("NoName4","Skull",336984.987000,-6105.892000,117783.933000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.501020,0.328280,0.747098,-0.288193


o=Bladex.CreateEntity("NoName0","Adoquinpulsador",330291.378000,-6453.915000,110767.020000)
o.Static=0
o.Scale=3.109114
o.Orientation=0.491198,0.491198,-0.508650,-0.508650


o=Bladex.CreateEntity("NoName0","Roca1Aurelio",281017.992000,-3282.817000,168135.537000)
o.Static=0
o.Scale=8.162250
o.Orientation=0.694115,0.183013,0.134922,-0.683013


o=Bladex.CreateEntity("NoName2","Roca1Aurelio",243051.955000,-4319.042000,122382.652000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.887011,0.461749,0.000000,0.000000


o=Bladex.CreateEntity("a2","Antorcha",294016.310000,682.446000,130017.892000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.023833,0.190036,-0.022792,0.981223
o.FiresIntensity=[ 44 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("a3","Antorcha",295666.860000,676.325000,130574.745000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.805890,0.114635,-0.568958,-0.116990
o.FiresIntensity=[ 38 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName3","Meson",324327.760000,130.380000,93590.773000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.500000,0.500000,0.500000,-0.500000


o=Bladex.CreateEntity("NoName4","Meson",333159.430000,130.347000,90360.749000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName5","Meson",336664.299000,137.916000,90411.367000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("banco5","Banco",324151.760000,360.963000,95036.301000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.517145,0.517145,0.482246,-0.482246


o=Bladex.CreateEntity("banco4","Banco",324501.269000,360.341000,92034.977000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650


o=Bladex.CreateEntity("banco1","Banco",335335.893000,365.497000,90285.772000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName12","Candelpeque",332785.013000,-573.242000,89784.257000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 27 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName13","Mortero",333091.230000,-448.433000,90840.158000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName14","Mortero",324278.886000,-455.539000,94197.832000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName15","Mortero",324928.931000,-511.283000,93777.600000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.836975,0.162691,0.512899,0.099697


o=Bladex.CreateEntity("NoName16","Palangana",323737.387000,-448.514000,93396.515000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 52 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName17","Palangana",336313.847000,-441.339000,91508.908000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 52 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName18","Palangana",333088.580000,-447.117000,91843.165000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 46 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName19","RollodeCuerda",333060.786000,-423.893000,88811.441000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName20","Tintero",336851.997000,-343.834000,89902.680000)
o.Static=0
o.Scale=1.115668
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName21","Velon",336273.940000,-442.424000,89223.050000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 40 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName24","Tabla_rota",341316.495000,706.978000,89797.895000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName25","Tabla_rota",339882.771000,693.845000,91834.729000)
o.Static=0
o.Scale=1.257163
o.Orientation=0.627211,0.627211,0.326506,-0.326506


o=Bladex.CreateEntity("cofre1","Cofre",352001.517000,202.402000,71456.175000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("cofre2","Cofre",352065.991000,195.079000,75111.989000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName2","Roca1Aurelio",300362.804000,-11976.370000,89172.212000)
o.Static=0
o.Scale=5.216126
o.Orientation=0.156123,0.227160,-0.544465,0.792201


o=Bladex.CreateEntity("NoName0","Antorcha2",345408.434000,-1103.264000,88509.556000)
o.Static=0
o.Scale=1.072135
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.531250,(255,128,0)) ]


o=Bladex.CreateEntity("NoName3","Pendon3",342483.467000,-9658.743000,98432.181000)
o.Static=0
o.Scale=2.130220
o.Orientation=0.000000,0.706891,0.000160,-0.707322


o=Bladex.CreateEntity("NoName4","Garfio",342798.507000,-13904.165000,98449.659000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.011564,0.662519,-0.013071,0.748842


o=Bladex.CreateEntity("NoName5","Antorcha2",342632.574000,-2955.652000,102692.602000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.531250,(255,128,0)) ]


o=Bladex.CreateEntity("barent1","Barril",296473.760000,-35.647000,124585.607000)
o.Static=0
o.Scale=1.871744
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barent2","Barril",295028.320000,20.058000,124794.242000)
o.Static=0
o.Scale=1.745810
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barent3","Barril",292876.029000,340.929000,125170.125000)
o.Static=0
o.Scale=1.321291
o.Orientation=0.982006,-0.011674,-0.062645,0.177774


o=Bladex.CreateEntity("barent5","Cajon2",292337.762000,80.045000,130362.013000)
o.Static=0
o.Scale=1.126825
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barent4","Cajon2",295019.399000,113.682000,126429.020000)
o.Static=0
o.Scale=1.072135
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Lanzapivotes",336418.826000,-6553.917000,125895.955000)
o.Static=0
o.Scale=4.027099
o.Orientation=0.495618,0.495618,0.504344,-0.504344


o=Bladex.CreateEntity("NoName1","Lamparatecho",361630.501000,-12092.165000,74679.904000)
o.Static=0
o.Scale=2.678033
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]


o=Bladex.CreateEntity("NoName2","Cuerda",361630.501000,-13542.165000,74679.904000)
o.Static=0
o.Scale=2.678033
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Varillaancha",339748.756000,-1922.605000,81500.728000)
o.Static=0
o.Scale=2.130220
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName1","Varillaancha",339571.158000,-3046.403000,81528.351000)
o.Static=0
o.Scale=2.130220
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName3","Varillaancha",339813.633000,-3822.641000,81597.646000)
o.Static=0
o.Scale=1.763268
o.Orientation=0.504344,0.504344,-0.495618,-0.495618


o=Bladex.CreateEntity("NoName0","Altar",381175.878000,598.355000,44857.532000)
o.Static=0
o.Scale=0.446651
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Armero",434349.114000,5161.328000,58071.050000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650


o=Bladex.CreateEntity("NoName1","Armero",434328.479000,5162.978000,56347.702000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.508650,0.508650,-0.491198,0.491198


o=Bladex.CreateEntity("pele1","Pelele",435278.952000,5011.208000,44818.346000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin3","Barril",431906.880000,5465.529000,52895.884000)
o.Static=0
o.Scale=1.269735
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin1","Barril",432287.262000,5314.284000,51041.016000)
o.Static=0
o.Scale=1.628348
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin2","Barril",431516.484000,5395.286000,51903.940000)
o.Static=0
o.Scale=1.430769
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin5","Barril",436603.412000,5377.962000,53353.034000)
o.Static=0
o.Scale=1.474123
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin6","Barril",436365.445000,5505.579000,51942.371000)
o.Static=0
o.Scale=1.172579
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barfin4","Barril",438832.013000,5359.000000,52134.753000)
o.Static=0
o.Scale=1.518790
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName0","Armero",500359.530000,9165.398000,43996.678000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName1","Armero",502315.327000,9164.603000,43882.765000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName2","Armero",504376.418000,9162.873000,44208.763000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName3","Antorchaenpared",434266.827000,4025.597000,69466.854000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.486740,0.553388,-0.512917,0.440184
o.FiresIntensity=[ 0 ]
o.Lights=[ (20.000000,0.031250,(255,158,51)) ]


o=Bladex.CreateEntity("NoName9","Antorchaenpared",498158.557000,8311.099000,39670.922000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.459229,0.560986,-0.537688,0.430459
o.FiresIntensity=[ 0 ]
o.Lights=[ (20.000000,0.431250,(255,145,21)) ]


o=Bladex.CreateEntity("pele2","Pelele",516839.221000,9063.722000,41386.154000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.545621,0.545621,0.449775,-0.449775


o=Bladex.CreateEntity("NoName0","Antorchaenpared",466190.165000,8158.409000,59816.255000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.703851,0.703851,-0.067773,-0.067773
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.631250,(255,155,45)) ]


o=Bladex.CreateEntity("barc1","Barril",485642.738000,9124.213000,47154.829000)
o.Static=0
o.Scale=2.088246
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("barc2","Barril",487643.785000,9493.608000,46707.183000)
o.Static=0
o.Scale=1.644632
o.Orientation=0.847923,-0.107926,-0.487115,0.179160


o=Bladex.CreateEntity("barc3","Barril",486634.873000,9112.936000,49347.549000)
o.Static=0
o.Scale=2.130220
o.Orientation=0.707107,0.707107,0.000000,0.000000


o=Bladex.CreateEntity("NoName4","Antorchaenpared",483316.625000,8174.747000,47566.905000)
o.Static=0
o.Scale=1.051010
o.Orientation=0.545621,0.459229,0.449775,-0.537688
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.231250,(255,154,43)) ]


o=Bladex.CreateEntity("NoName5","Antorchaenpared",450405.386000,5804.294000,40984.843000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.482246,0.541675,-0.517145,0.454519
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.231250,(251,132,0)) ]


o=Bladex.CreateEntity("NoName6","Antorchaenpared",417454.411000,1586.204000,60070.268000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.705384,0.705384,-0.049325,-0.049325
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.231250,(255,149,32)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",521958.516000,8066.992000,26137.977000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.531250,(255,140,13)) ]


o=Bladex.CreateEntity("NoName0","Antorchaenpared",521719.423824,8125.642971,38203.966103)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(168,88,0)) ]


o=Bladex.CreateEntity("poc2","Pocima100",337072.045000,-6207.614000,120672.828000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.RemoveFromWorld()

o=Bladex.CreateEntity("poc1","Pocima100",336856.241000,-6207.817000,121297.611000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.RemoveFromWorld()