import Reference
import Bladex
# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 143 Items.

o=Bladex.CreateEntity("luzrey3","Lampcolg",93146.185000,-1428.658000,857.229000,Reference.ObjType("Lampcolg"))
o.Scale=1.361327
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (7.000000,0.070000,(255,168,23)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Lampared",44989.526000,3849.587000,-15885.741000,Reference.ObjType("Lampared"))
o.Scale=1.257163
o.Orientation=0.653282,0.653282,-0.270598,0.270598
o.FiresIntensity=[ 33 ]
o.Lights=[ (0.000000,0.053448,(191,165,96)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Lampared",64414.061000,4817.195000,42960.149000,Reference.ObjType("Lampared"))
o.Scale=1.208109
o.Orientation=0.000000,0.000000,0.707107,-0.707107
o.FiresIntensity=[ 32 ]
o.Lights=[ (0.000000,0.120000,(255,147,28)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Lampared",5839.425000,-3278.601000,34857.160000,Reference.ObjType("Lampared"))
o.Scale=1.402577
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 26 ]
o.Lights=[ (0.000000,0.120000,(255,159,53)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI4","Lapida",71897.125000,5246.332000,-3445.447000,Reference.ObjType("Lapida"))
o.Scale=1.488864
o.Orientation=0.500000,0.500000,0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI2","Lapida",73659.861000,5380.273000,6649.635000,Reference.ObjType("Lapida"))
o.Scale=1.402577
o.Orientation=0.572061,0.508650,0.415627,-0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI6","Lapida",59736.515000,5170.197000,-2744.217000,Reference.ObjType("Lapida"))
o.Scale=1.661078
o.Orientation=0.549525,0.491198,0.444997,-0.508650
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI1","Obelisco",75523.970000,4393.305000,745.748000,Reference.ObjType("Obelisco"))
o.Scale=3.609585
o.Orientation=0.688355,0.725374,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI3","Lapida3",69233.364000,5268.334000,2911.317000,Reference.ObjType("Lapida3"))
o.Scale=1.580459
o.Orientation=0.477714,0.430459,0.521334,-0.560986
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI5","Lapida3",63927.933000,5597.633000,767.402000,Reference.ObjType("Lapida3"))
o.Scale=1.816697
o.Orientation=0.454519,0.454519,0.541675,-0.541675
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI8","Lapida3",53246.168000,5127.131000,-3448.750000,Reference.ObjType("Lapida3"))
o.Scale=1.518790
o.Orientation=0.459229,0.459229,0.537688,-0.537688
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName18","Garfio",93154.080000,-2355.004000,885.447000,Reference.ObjType("Garfio"))
o.Scale=1.430769
o.Orientation=0.624338,0.624338,0.331967,-0.331967
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName19","Armero",98249.730000,4053.300000,-11291.042000,Reference.ObjType("Armero"))
o.Scale=1.126825
o.Orientation=0.030844,0.030844,0.706434,-0.706434
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo13","Roca2",80348.043000,5684.468000,26709.691000,Reference.ObjType("Roca2"))
o.Scale=1.308209
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo12","Roca1",75320.312000,6162.699000,20028.754000,Reference.ObjType("Roca1"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo9","Columnaestrecha",-13301.412000,242.956000,-18859.612000,Reference.ObjType("Columnaestrecha"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo8","Columnaestrecha",-13050.801000,240.513000,-8868.764000,Reference.ObjType("Columnaestrecha"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo7","Columnaestrecha",-13180.873000,242.830000,5588.697000,Reference.ObjType("Columnaestrecha"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo6","Columnaestrecha",-13317.270000,186.794000,15657.858000,Reference.ObjType("Columnaestrecha"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName55","Gancholamp",-7457.744000,105.387000,-38998.008000,Reference.ObjType("Gancholamp"))
o.Scale=1.488864
o.Orientation=0.000000,0.000000,0.713250,-0.700909
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName56","Lampcolg",-7471.928000,496.596000,-38625.008000,Reference.ObjType("Lampcolg"))
o.Scale=1.361327
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 33 ]
o.Lights=[ (0.000000,0.128629,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero10","Astillas2",-6175.760000,5789.025000,-38311.254000,Reference.ObjType("Astillas2"))
o.Scale=1.000000
o.Orientation=0.560986,0.560986,0.430459,-0.430459
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero9","Astillas3",-8460.149000,5807.227000,-37878.566000,Reference.ObjType("Astillas3"))
o.Scale=1.000000
o.Orientation=0.353553,0.353553,0.612372,-0.612373
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName59","Astillas1",-3874.598000,6316.325000,-38849.490000,Reference.ObjType("Astillas1"))
o.Scale=1.000000
o.Orientation=0.621418,0.621418,-0.337402,0.337402
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero8","Astillas2",-6227.344000,5340.533000,-37944.007000,Reference.ObjType("Astillas2"))
o.Scale=1.115668
o.Orientation=0.786291,0.581824,-0.167131,0.123671
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName61","Hoguera",45849.486000,5762.149000,-38479.528000,Reference.ObjType("Hoguera"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 52 ]
o.Lights=[ (0.000000,0.120000,(255,145,21)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo10","Roca1",51061.356000,5332.418000,-37216.594000,Reference.ObjType("Roca1"))
o.Scale=1.000000
o.Orientation=0.537300,0.843391,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero8","Astillas3",43838.471000,5823.264000,-37874.195000,Reference.ObjType("Astillas3"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("7","Astillas2",46876.806000,5791.775000,-36695.419000,Reference.ObjType("Astillas2"))
o.Scale=1.000000
o.Orientation=0.627211,0.627211,-0.326506,0.326506
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero6","Taburete",47576.907000,5703.950000,-39327.565000,Reference.ObjType("Taburete"))
o.Scale=1.000000
o.Orientation=0.687569,0.687569,0.165071,-0.165071
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName69","Garfio3",1425.456000,-1550.448000,-35936.822000,Reference.ObjType("Garfio3"))
o.Scale=1.711410
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName70","Lampcolg",1508.406000,-584.106000,-35926.260000,Reference.ObjType("Lampcolg"))
o.Scale=1.474123
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.031250,(255,164,62)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName71","Roca2",-22073.982000,3973.630000,26324.584000,Reference.ObjType("Roca2"))
o.Scale=4.317595
o.Orientation=0.541675,0.541675,0.454519,-0.454519
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LAPI7","Lapida",54313.694000,5097.977000,2451.177000,Reference.ObjType("Lapida"))
o.Scale=1.780901
o.Orientation=0.508650,0.508650,0.491198,-0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName73","LamparaMiguel",-22880.211000,267.180000,-3636.798000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.745810
o.Orientation=0.482246,0.482246,-0.517145,0.517145
o.FiresIntensity=[ 37 ]
o.Lights=[ (0.000000,0.240000,(255,173,83)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName75","LamparaMiguel",-23015.588000,334.074000,-16249.225000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.488864
o.Orientation=0.477714,0.477714,-0.521334,0.521334
o.FiresIntensity=[ 40 ]
o.Lights=[ (0.000000,0.200000,(255,176,89)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName76","LamparaMiguel",19146.333000,-3663.079000,-19646.346000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.269735
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 27 ]
o.Lights=[ (0.000000,0.150000,(227,157,79)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("luzrey2","LamparaMiguel",92499.526000,838.102000,-9771.029000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.012342,0.012341,0.706999,-0.706999
o.FiresIntensity=[ 25 ]
o.Lights=[ (0.000000,0.180993,(255,155,81)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName86","Lamparatecho",18321.620000,-19501.873000,-1337.881000,Reference.ObjType("Lamparatecho"))
o.Scale=5.268286
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 33 ]
o.Lights=[ (0.000000,0.100000,(237,180,92)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName92","Palangana",34692.796000,-5747.490000,-1440.891000,Reference.ObjType("Palangana"))
o.Scale=1.282432
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.764935,2.219816,(177,205,204)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName94","Lampared",42034.288000,-3228.571000,13808.895000,Reference.ObjType("Lampared"))
o.Scale=1.000000
o.Orientation=0.486740,0.486740,0.512917,-0.512917
o.FiresIntensity=[ 10 ]
o.Lights=[ (1.885636,0.008789,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName95","Lampared",38350.790000,-756.953000,-10953.955000,Reference.ObjType("Lampared"))
o.Scale=1.000000
o.Orientation=0.495618,0.495618,-0.504344,0.504344
o.FiresIntensity=[ 3 ]
o.Lights=[ (8.149597,0.031250,(255,163,60)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName96","Lampared",38349.641000,-769.843000,8086.111000,Reference.ObjType("Lampared"))
o.Scale=1.000000
o.Orientation=0.504344,0.504344,-0.495618,0.495618
o.FiresIntensity=[ 8 ]
o.Lights=[ (7.000000,0.040000,(255,151,36)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName97","LamparaMiguel",37908.198000,-5464.062000,-1496.077000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.504344,0.504344,-0.495618,0.495618
o.FiresIntensity=[ 31 ]
o.Lights=[ (0.000000,0.111115,(255,174,85)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero6","Arbolseco2",76374.558000,2857.948000,-4559.350000,Reference.ObjType("Arbolseco2"))
o.Scale=1.430768
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName103","Rama1",74547.612000,2383.998000,-5066.135000,Reference.ObjType("Rama1"))
o.Scale=1.172579
o.Orientation=0.594719,0.553809,-0.454503,0.364735
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero4","Arbolseco2",35533.856000,-2865.866000,21549.447000,Reference.ObjType("Arbolseco2"))
o.Scale=1.890462
o.Orientation=0.652138,0.663621,-0.261407,0.256884
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName107","Rama1",34122.326000,-6266.616000,19336.464000,Reference.ObjType("Rama1"))
o.Scale=1.816697
o.Orientation=0.188966,0.188966,-0.681390,0.681390
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero5","Arbolseco2",76159.937000,3258.053000,24108.653000,Reference.ObjType("Arbolseco2"))
o.Scale=1.388690
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName109","Rama2",73842.229000,3356.762000,23554.616000,Reference.ObjType("Rama2"))
o.Scale=1.816697
o.Orientation=0.863413,0.227626,-0.440292,0.094059
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName112","LamparaMiguel",-34370.476000,2307.965000,-2885.222000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.138093
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 35 ]
o.Lights=[ (0.000000,0.090000,(255,163,60)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName114","LamparaMiguel",-31029.298000,-9028.100000,-10255.796000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.521334,0.521334,-0.477714,0.477714
o.FiresIntensity=[ 23 ]
o.Lights=[ (0.000000,0.060000,(255,165,66)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName116","Lampcolg",-39681.487000,-7620.911000,-9189.849000,Reference.ObjType("Lampcolg"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 54 ]
o.Lights=[ (0.000000,0.100000,(197,160,86)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName126","Candil",38149.126000,3897.043000,12985.240000,Reference.ObjType("Candil"))
o.Scale=1.184304
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 5 ]
o.Lights=[ (1.000000,0.070000,(253,133,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName127","Candil",38146.817000,3909.845000,-13716.285000,Reference.ObjType("Candil"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 8 ]
o.Lights=[ (1.000000,0.050000,(255,147,28)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName140","Palangana",28657.223000,3939.017000,-14535.575000,Reference.ObjType("Palangana"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (5.000000,0.060000,(255,156,47)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName141","Columna",28554.786000,4558.184000,-14533.483000,Reference.ObjType("Columna"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero2","Taburete",-39670.378000,-4842.347000,-13169.350000,Reference.ObjType("Taburete"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero3","Taburete",-39268.027000,-4840.067000,-9125.305000,Reference.ObjType("Taburete"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName264","Gancholamp",-39940.994000,-7912.350000,-9182.511000,Reference.ObjType("Gancholamp"))
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero1","Arbolseco2",-39902.613000,3835.241000,-34853.089000,Reference.ObjType("Arbolseco2"))
o.Scale=1.474123
o.Orientation=0.641781,0.664583,0.275279,-0.265834
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName282","Rama1",-41573.970000,2067.010000,-33976.820000,Reference.ObjType("Rama1"))
o.Scale=1.334504
o.Orientation=0.643440,0.643440,-0.293232,0.293232
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName283","Rama2",-39922.536000,3291.728000,-35195.936000,Reference.ObjType("Rama2"))
o.Scale=1.644632
o.Orientation=0.516556,0.335494,0.736174,0.280467
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName296","Varillaancha",86180.875000,-11739.441000,-22273.616000,Reference.ObjType("Varillaancha"))
o.Scale=1.518791
o.Orientation=0.212631,-0.674380,0.674380,-0.212631
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName297","Varillaancha",85622.014000,-11772.219000,-22301.950000,Reference.ObjType("Varillaancha"))
o.Scale=1.416603
o.Orientation=0.500000,0.500000,0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja3","Varillaancha",85695.328000,-4771.753000,-22378.307000,Reference.ObjType("Varillaancha"))
o.Scale=1.104623
o.Orientation=0.491198,0.508650,0.491198,0.508650
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja4","Varillaancha",86112.393000,-4899.453000,-22337.934000,Reference.ObjType("Varillaancha"))
o.Scale=1.232391
o.Orientation=0.012342,-0.706999,0.706999,-0.012341
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName300","Roca2",-71611.646000,15727.283000,-31129.940000,Reference.ObjType("Roca2"))
o.Scale=5.648316
o.Orientation=0.522499,0.852640,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName301","Roca1",-73096.496000,17398.123000,-55283.645000,Reference.ObjType("Roca1"))
o.Scale=2.625265
o.Orientation=0.484240,0.678879,0.449340,0.320511
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName304","Roca1",-58055.480000,14725.653000,26515.328000,Reference.ObjType("Roca1"))
o.Scale=2.928926
o.Orientation=0.687569,0.687569,-0.165071,-0.165071
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName305","Roca2",-43493.657000,8282.320000,34550.602000,Reference.ObjType("Roca2"))
o.Scale=3.366725
o.Orientation=0.579228,0.579228,0.405580,-0.405580
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("luzrey4","Candil2",108996.865000,-3252.118000,748.425000,Reference.ObjType("Candil2"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 35 ]
o.Lights=[ (0.000000,0.100000,(255,112,34)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo11","Columna",97862.623000,2296.689000,12070.646000,Reference.ObjType("Columna"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Lampared",50432.871000,4632.209000,29904.417000,Reference.ObjType("Lampared"))
o.Scale=1.000000
o.Orientation=0.006164,0.006171,0.707080,-0.707080
o.FiresIntensity=[ 29 ]
o.Lights=[ (0.000000,0.120000,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp303","LamparaMiguel",28351.310000,2931.575000,9854.065000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.018510,0.018510,-0.706864,0.706864
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.000000,0.060000,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp319","LamparaMiguel",11494.455000,4173.179000,-15852.303000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (16.000000,0.070000,(255,164,62)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja6","Reja",27530.638000,5383.436000,1303.790000,Reference.ObjType("Reja"))
o.Scale=2.548057
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja7","Reja",27583.293000,5271.861000,-4266.759000,Reference.ObjType("Reja"))
o.Scale=2.522829
o.Orientation=0.504344,0.504344,-0.495618,0.495618
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja1","Reja",-41291.371000,5094.889000,-53949.242000,Reference.ObjType("Reja"))
o.Scale=2.871214
o.Orientation=0.660141,0.660141,0.253404,-0.253404
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("rastrillo6","Rastrillo",-26029.250000,4470.939000,-50491.316000,Reference.ObjType("Rastrillo"))
o.Scale=1.196147
o.Orientation=0.491198,0.491198,-0.508650,0.508650
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("luzrey1","LamparaMiguel",92542.841000,754.069000,11261.129000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 25 ]
o.Lights=[ (0.000000,0.070000,(254,126,22)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp357","ReinaAurelio",35372.961000,-5148.490000,-1468.430000,Reference.ObjType("ReinaAurelio"))
o.Scale=3.756148
o.Orientation=0.482246,0.482246,0.517145,-0.517145
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp359","Roca1Aurelio",-40499.497000,15802.661000,-1365.869000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.842787
o.Orientation=0.147809,0.989016,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp360","Roca1Aurelio",-60674.460000,17222.837000,-8292.264000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.400385
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo1","Roca1Aurelio",-30131.766000,7021.748000,-37435.122000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.194768
o.Orientation=0.541675,0.541675,0.454519,-0.454519
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp381","Candil2",-21944.348000,-8071.225000,28930.655000,Reference.ObjType("Candil2"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 47 ]
o.Lights=[ (0.000000,0.100000,(193,119,36)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp384","Garfio2",-21939.083000,-8852.690000,28925.921000,Reference.ObjType("Garfio2"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp385","Varilla",108931.365000,-4219.503000,707.532000,Reference.ObjType("Varilla"))
o.Scale=1.402577
o.Orientation=0.508650,0.508650,-0.491198,0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp386","Garfio2",108975.834000,-3989.516000,721.401000,Reference.ObjType("Garfio2"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp387","Antorchaenpared",124926.994000,3373.688000,-7147.892000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.043168,0.043168,0.705788,-0.705788
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.031250,(255,151,36)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp390","Antorchaenpared",150057.142000,6358.473000,4193.103000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.486435,0.478019,0.512613,-0.521639
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.050000,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp393","VigaPlana",-39599.410000,-1656.972000,-23216.522000,Reference.ObjType("VigaPlana"))
o.Scale=2.306723
o.Orientation=0.419273,0.562950,0.566151,-0.432170
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo2","Adoquinpulsador",-40622.002000,7269.321000,-25974.624000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.448632
o.Orientation=0.719017,-0.624303,0.222874,0.208775
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo4","Adoquinpulsador",-40965.241000,1828.998000,-19556.298000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.651518
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp396","Adoquinpulsador",-40012.475000,2274.235000,-20577.767000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.400392
o.Orientation=0.505065,0.496418,-0.536888,0.458509
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp397","Adoquinpulsador",-41469.820000,2895.417000,-21644.453000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.599273
o.Orientation=0.486514,0.521564,0.486971,-0.504118
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo5","Adoquinpulsador",-39937.064000,577.479000,-19419.274000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.538461
o.Orientation=0.501705,0.452461,-0.548261,0.492932
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo3","Adoquinpulsador",-42878.376000,5155.097000,-20220.349000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.109114
o.Orientation=0.495618,0.495618,-0.504344,0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp400","Adoquinpulsador",-22536.905000,-5611.471000,-38391.020000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.497850
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp401","Adoquinpulsador",-17205.682000,6222.934000,5014.469000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.548057
o.Orientation=0.719846,0.604023,-0.262003,0.219846
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo21","Adoquinpulsador",-13354.225000,362.495000,34155.937000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.573537
o.Orientation=0.463904,0.463904,-0.533660,0.533660
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp403","Adoquinpulsador",-28098.804000,-6012.992000,-19925.999000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.538461
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp413","Adoquinpulsador",43541.811000,17.892000,-16564.438000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.718959
o.Orientation=0.504344,0.504344,-0.495618,0.495618
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName20","Adoquinpulsador",83979.313000,-38.641000,-15696.676000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.842787
o.Orientation=0.606109,0.691655,-0.364187,0.147016
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo16","Adoquinpulsador",54005.617000,2509.824000,17199.277000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.625266
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo17","Adoquinpulsador",52726.861000,3038.928000,18352.864000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.130220
o.Orientation=0.014591,-0.725129,0.010081,-0.688385
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo14","Adoquinpulsador",53627.340000,6469.664000,21378.880000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.047852
o.Orientation=0.645974,0.508650,-0.287606,0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo15","Adoquinpulsador",52269.499000,6653.777000,24668.506000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.235356
o.Orientation=0.728716,0.633982,0.129132,-0.224421
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp428","Piedra_09",-39043.689000,6815.481000,-25199.374000,Reference.ObjType("Piedra_09"))
o.Scale=1.000000
o.Orientation=0.256519,-0.948684,-0.103079,0.153527
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName26","Piedra_01",-43051.485000,5416.188000,-22737.464000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.970897,-0.155708,-0.064488,0.170163
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName27","Piedra_01",-40328.570000,2310.677000,-22976.159000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.987391,-0.075651,-0.049521,0.129940
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo6","Adoquinpulsador",-38740.998000,-2254.729000,-20333.522000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.078330
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp464","Piedra_01",34842.073000,5907.601000,-33980.784000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.984820,-0.090528,-0.064923,0.133117
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp465","Piedra_01",35456.473000,5908.892000,-34669.702000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.966011,-0.159134,-0.126928,0.159338
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp466","Piedra_03",33624.212000,5879.946000,-36203.575000,Reference.ObjType("Piedra_03"))
o.Scale=1.000000
o.Orientation=0.656414,0.750173,-0.043410,-0.066902
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("laftablilla","LamparaMiguel",160839.071000,5861.189000,7564.818000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.000000
o.Orientation=0.683013,0.683013,-0.183013,0.183013
o.FiresIntensity=[ 43 ]
o.Lights=[ (0.000000,0.090000,(255,159,53)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName534","Seta",52989.506000,5960.404000,-3188.255000,Reference.ObjType("Seta"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName535","Seta",52842.179000,5926.143000,-3326.666000,Reference.ObjType("Seta"))
o.Scale=1.000000
o.Orientation=0.379928,0.379928,0.596368,-0.596368
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName536","Seta",76034.330000,5958.046000,-5769.636000,Reference.ObjType("Seta"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName537","Seta",75876.168000,5964.963000,-5993.783000,Reference.ObjType("Seta"))
o.Scale=1.000000
o.Orientation=0.575667,0.575667,-0.410619,0.410619
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName538","Seta",76174.332000,5964.418000,-5979.076000,Reference.ObjType("Seta"))
o.Scale=1.000000
o.Orientation=0.537688,0.537688,0.459229,-0.459229
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Reja",-856.336000,-10014.878000,-1473.381000,Reference.ObjType("Reja"))
o.Scale=2.842787
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Reja",-9654.434000,5241.281000,4770.519000,Reference.ObjType("Reja"))
o.Scale=3.109114
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","LamparaMiguel",-10763.374000,-5046.526000,34678.640000,Reference.ObjType("LamparaMiguel"))
o.Scale=1.564811
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 29 ]
o.Lights=[ (0.000000,0.100000,(255,171,79)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorchaenpared",-31025.607000,-6358.421000,-15085.797000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 74 ]
o.Lights=[ (0.000000,0.090000,(255,160,55)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Antorchaenpared",54623.273000,3732.560000,28150.855000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.435338,0.435338,0.557208,-0.557208
o.FiresIntensity=[ 1 ]
o.Lights=[ (10.000000,0.100000,(255,145,21)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo20","Adoquinpulsador",48736.997000,6112.619000,49810.125000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.047099
o.Orientation=0.006724,-0.763885,0.026470,-0.644774
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo18","Adoquinpulsador",49252.693000,6428.866000,48039.224000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.834864
o.Orientation=0.000000,0.979621,-0.001992,0.200843
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Adoquinpulsador",49828.558000,6100.005000,49872.574000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.564811
o.Orientation=0.569724,0.422829,0.422579,0.563966
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo19","Adoquinpulsador",48758.155000,4844.750000,49781.960000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.400385
o.Orientation=0.657349,0.725783,0.050113,-0.196518
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Adoquinpulsador",48037.661000,3994.248000,49589.486000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.533978
o.Orientation=0.446792,0.343511,-0.642360,0.519376
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Adoquinpulsador",49619.416000,3379.375000,49791.397000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.497850
o.Orientation=0.575667,0.575667,-0.410619,0.410619
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Hoguera",49820.115000,6673.507000,44616.297000,Reference.ObjType("Hoguera"))
o.Scale=1.728525
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.090000,(255,145,23)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha",88912.678000,3920.643000,-6553.367000,Reference.ObjType("Antorcha"))
o.Scale=1.000000
o.Orientation=0.215828,0.785207,-0.458697,-0.355620
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.080000,(255,160,55)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","EsqueletoPieza10",59696.964000,6259.649000,26320.773000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.058399,-0.832740,0.492739,-0.245646
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","EsqueletoPieza2",59521.154000,6277.630000,27106.694000,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.913545,0.406737,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","EsqueletoPieza1",59254.032000,6291.628000,26414.189000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.993572,0.113203,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","EsqueletoPieza4",58379.247000,6233.082000,26520.478000,Reference.ObjType("EsqueletoPieza4"))
o.Scale=1.000000
o.Orientation=0.000000,0.857167,0.000000,-0.515038
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","EsqueletoPieza2",71463.981000,6197.712000,23870.905000,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.718034,0.181519,0.541451,-0.397880
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","EsqueletoPieza1",70479.991000,6203.081000,24194.449000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.641907,-0.033641,0.764995,-0.040092
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","EsqueletoPieza4",69805.841000,6249.278000,23667.644000,Reference.ObjType("EsqueletoPieza4"))
o.Scale=1.000000
o.Orientation=0.390920,-0.604075,0.565602,-0.402950
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Hoguera",26798.758000,782.652000,-21608.991000,Reference.ObjType("Hoguera"))
o.Scale=1.402577
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 8 ]
o.Lights=[ (6.000000,0.031250,(244,129,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Hoguera",-10238.525000,718.945000,34024.068000,Reference.ObjType("Hoguera"))
o.Scale=1.596263
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 9 ]
o.Lights=[ (8.000000,0.100000,(255,156,47)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


