# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 61 Items.

o=Bladex.CreateEntity("NoName0","Arbolseco",3242.175000,-5215.375000,-3311.376000,"Physic")
o.Scale=2.651518
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Arbolseco2",-5835.066000,-2930.939000,-13689.047000,"Physic")
o.Scale=1.580459
o.Orientation=0.337402,0.337402,-0.621418,0.621418
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Hoguera",15644.024000,-761.497000,13836.743000,"Physic")
o.Scale=1.488864
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (12.000000,0.120000,(249,131,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Roca2Aurelio",-8586.152000,667.358000,-19541.841000,"Physic")
o.Scale=4.675337
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Roca1Aurelio",-12669.860000,1544.737000,3334.604000,"Physic")
o.Scale=2.238882
o.Orientation=0.521334,0.521334,0.477714,0.477714
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",11708.988000,-9198.962000,-2675.845000,"Physic")
o.Scale=1.000000
o.Orientation=0.713250,0.700909,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (2.000000,0.090000,(255,142,17)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Viga",19594.096000,-11509.773000,-149.378000,"Physic")
o.Scale=3.609585
o.Orientation=0.504192,0.486892,0.495465,-0.513069
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Viga",19916.871000,-11582.586000,-5718.823000,"Physic")
o.Scale=3.267710
o.Orientation=0.495618,0.495618,0.504344,-0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Adoquinpulsador",21051.965000,-10474.223000,-14575.659000,"Physic")
o.Scale=2.497850
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Adoquinpulsador",9116.053000,-946.420000,-17269.931000,"Physic")
o.Scale=1.728525
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Adoquinpulsador",19609.580000,-7707.360000,-10250.442000,"Physic")
o.Scale=1.564811
o.Orientation=0.683013,0.683013,-0.183013,0.183013
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Vigaro1",12794.309000,-10517.421000,-10824.277000,"Physic")
o.Scale=1.000000
o.Orientation=0.318006,0.620874,0.351808,-0.624194
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Vigaro1",20717.640000,-13586.012000,-10879.573000,"Physic")
o.Scale=1.000000
o.Orientation=0.602728,0.414243,-0.562053,0.386288
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Roca1Aurelio",-19641.152000,1048.522000,-37194.435000,"Physic")
o.Scale=5.648317
o.Orientation=0.457969,0.138850,0.266199,0.836734
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Roca2Aurelio",-31944.313000,-2616.507000,-24843.067000,"Physic")
o.Scale=3.793710
o.Orientation=0.648057,-0.679716,0.076673,0.334857
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Roca2Aurelio",-28246.590000,-2546.401000,5077.332000,"Physic")
o.Scale=2.899927
o.Orientation=0.358400,0.062844,-0.897754,-0.248268
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",23696.371000,-5027.117000,-4427.677000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(255,138,9)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Hoguera",-1465.402000,-190.033000,26357.343000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 7 ]
o.Lights=[ (7.000000,0.100000,(255,160,55)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Tronco",12597.029000,-503.874000,12232.000000,"Physic")
o.Scale=1.763268
o.Orientation=0.533660,0.533660,-0.463904,0.463904
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Tronco",11894.934000,-412.620000,11948.602000,"Physic")
o.Scale=1.533978
o.Orientation=0.644943,-0.065820,0.286723,0.705342
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Tronco",11761.030000,-758.393000,12220.320000,"Physic")
o.Scale=1.533978
o.Orientation=0.627416,-0.042631,0.326026,0.705860
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Taburete",16469.679000,-586.973000,11282.631000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Tabla_rota",19427.279000,-469.441000,13589.910000,"Physic")
o.Scale=1.533978
o.Orientation=0.686950,-0.703930,0.048123,0.173973
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Tabla_rota",17045.419000,-8052.803000,-12542.879000,"Physic")
o.Scale=1.928460
o.Orientation=0.601361,0.305024,-0.334970,0.658119
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Tabla_rota",13961.291000,-7357.743000,-4398.666000,"Physic")
o.Scale=1.402577
o.Orientation=0.259156,0.259156,0.657904,-0.657904
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Tabla_rota",13423.129000,-7433.418000,-4223.460000,"Physic")
o.Scale=1.533978
o.Orientation=0.574578,0.558923,0.393531,-0.450110
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Tabla_rota",19884.834000,-7371.524000,-6404.586000,"Physic")
o.Scale=1.780901
o.Orientation=0.599660,0.599660,-0.374710,0.374710
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",18260.477000,-1803.945000,27033.360000,"Physic")
o.Scale=1.000000
o.Orientation=0.440184,0.440184,0.553388,-0.553388
o.FiresIntensity=[ 5 ]
o.Lights=[ (9.000000,0.090000,(255,153,40)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Arbolseco2",12384.843000,-9581.506000,-27356.536000,"Physic")
o.Scale=2.173037
o.Orientation=0.798635,0.601815,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Menhir1",18656.367000,-10181.822000,-14639.410000,"Physic")
o.Scale=0.258400
o.Orientation=0.047656,-0.676211,-0.028377,0.734617
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Perola",14628.168000,-767.440000,13185.221000,"Physic")
o.Scale=1.388690
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Palangana",12619.858000,-409.823000,10758.923000,"Physic")
o.Scale=1.149474
o.Orientation=0.642764,0.766015,0.006685,-0.005609
o.FiresIntensity=[ 34 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Menhir2",11219.447000,-7881.785000,-13881.597000,"Physic")
o.Scale=0.483659
o.Orientation=0.719340,0.000000,-0.694658,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Menhir2",1389.603000,-10861.091000,16944.379000,"Physic")
o.Scale=0.698925
o.Orientation=0.040673,-0.628458,0.776081,-0.032936
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Menhir1",-8534.313000,-7527.163000,27139.186000,"Physic")
o.Scale=0.645445
o.Orientation=0.000000,1.000000,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Jarra",16176.570000,-810.187000,23393.215000,"Physic")
o.Scale=1.347849
o.Orientation=0.657904,0.657904,-0.259156,0.259156
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Paletilla",12641.566000,-434.755000,10564.235000,"Physic")
o.Scale=1.126825
o.Orientation=0.784398,0.584959,0.070553,0.193816
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Mortero",11255.425000,-2034.490000,9070.616000,"Physic")
o.Scale=1.000000
o.Orientation=0.218508,0.218508,-0.672499,0.672499
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Menhir1",-867.245000,-160.369000,16833.343000,"Physic")
o.Scale=0.442229
o.Orientation=0.082435,-0.720672,-0.682426,0.090169
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Menhir1",14476.837000,-973.075000,22626.461000,"Physic")
o.Scale=0.277040
o.Orientation=0.000000,0.999048,0.000016,-0.043619
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Hacha",11267.052000,-659.860000,8824.209000,"Physic")
o.Scale=1.000000
o.Orientation=0.164965,0.220969,0.788769,0.549366
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Tabla_xl",11234.041000,-1825.903000,8121.348000,"Physic")
o.Scale=1.928460
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Jarra",11213.412000,-2086.583000,8579.692000,"Physic")
o.Scale=1.763268
o.Orientation=0.640856,0.640856,0.298836,-0.298836
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Menhir2",7172.133000,-43.847000,-8207.953000,"Physic")
o.Scale=1.000000
o.Orientation=0.483697,0.425163,0.556430,0.525032
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Menhir1",1456.318000,117.338000,-8384.052000,"Physic")
o.Scale=0.578528
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Menhir1",-1780.436000,425.668000,-8340.251000,"Physic")
o.Scale=0.518548
o.Orientation=0.500000,0.500000,0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Rama1",-1230.018000,-468.010000,-6663.583000,"Physic")
o.Scale=1.000000
o.Orientation=0.340999,0.590628,-0.365677,0.633371
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Rama2",-762.981000,-182.520000,-6666.363000,"Physic")
o.Scale=1.149474
o.Orientation=0.153046,0.153046,0.690346,-0.690346
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Tabla_xl",10439.075000,-1684.738000,9326.688000,"Physic")
o.Scale=1.232392
o.Orientation=0.026128,0.043604,-0.001598,0.998706
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Tabla_xl",10612.211000,-1686.516000,8417.091000,"Physic")
o.Scale=1.000000
o.Orientation=0.017452,-0.999848,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Menhir1",-1625.557000,-161.349000,-10334.691000,"Physic")
o.Scale=0.705914
o.Orientation=0.712273,0.699949,-0.037329,-0.036683
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Menhir2",2847.635000,35.237000,3317.861000,"Physic")
o.Scale=0.844377
o.Orientation=0.054849,0.679403,0.728571,-0.067733
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName12","Rama1",-3964.983000,-3.759000,-9425.383000,"Physic")
o.Scale=1.172579
o.Orientation=0.586218,0.586218,-0.395409,0.395409
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName13","Arbolseco",-5601.611000,-892.497000,3338.764000,"Physic")
o.Scale=1.334504
o.Orientation=0.678294,0.527604,-0.465169,-0.212529
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Rama1",15912.159000,-593.625000,24589.324000,"Physic")
o.Scale=1.115668
o.Orientation=0.153046,0.153046,0.690346,-0.690346
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Rama2",15481.818000,-643.258000,25917.400000,"Physic")
o.Scale=1.257163
o.Orientation=0.703851,0.703851,0.067773,-0.067773
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Roca1Aurelio",17882.510000,399.030000,27466.538000,"Physic")
o.Scale=1.232392
o.Orientation=0.701836,0.579228,-0.086175,0.405580
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Roca2Aurelio",-333.904000,737.909000,-5412.307000,"Physic")
o.Scale=1.115668
o.Orientation=0.147015,-0.061628,0.704416,0.691655
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Rama1",16145.797000,-767.248000,25072.281000,"Physic")
o.Scale=1.596263
o.Orientation=0.469472,0.882948,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Rama2",15609.449000,-1200.092000,24488.602000,"Physic")
o.Scale=0.658419
o.Orientation=0.769231,0.458757,-0.411415,0.169004
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Arbolseco",18739.629000,-1789.765000,24512.112000,"Physic")
o.Scale=1.503752
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


