# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 2 Items.

o=Bladex.CreateEntity("NoName0","Escudo3",-48836.260521,11392.080440,-8014.277810,"Physic")
o.Scale=8.664392
o.Orientation=0.997564,0.069756,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Escudon",-59700.978911,13298.512136,-2322.364941,"Physic")
o.Scale=4.913826
o.Orientation=0.998630,0.052336,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


