# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 5 Items.

o=Bladex.CreateEntity("NoName0","Antorcha",-17981.923000,14575.823000,-7345.061000)
o.Static=0
o.Scale=1.000000
o.Orientation=0.999496,0.024744,0.019870,-0.000734
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.080000,(255,165,66)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorcha",-57533.984000,15092.612000,-6576.963000)
o.Static=0
o.Scale=1.104622
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 4 ]
o.Lights=[ (4.000000,0.080000,(198,104,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorcha",-56316.530435,15164.730683,-19724.974683)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (4.000000,0.080000,(206,108,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Antorcha",-78379.699329,15168.904571,-1797.823778)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (4.000000,0.080000,(215,113,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Antorcha",-102433.620428,15052.814500,-2225.119774)
o.Static=0
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 7 ]
o.Lights=[ (4.000000,0.080000,(234,123,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


