import Bladex
import LoadBar
LoadBar.ECTSProgressBar(449,"Blade_progress.jpg")

execfile("../../Scripts/sys_init.py")

#BBLib.GetnOpenedInputFiles()

Bladex.ReadLevel("tower.lvl")

execfile("../../Scripts/BladeInit.py")


#char=Bladex.GetEntity("Player1")
#char.Position= 24250,3000,44000	

# Item configuration script
# Script generated by LED: Aug  5 1998 19:56:40

execfile("ActorsInit.py")
execfile("MusicEvents.py")
execfile("Musica.py")


execfile("DefFuncs.py")

execfile("TextureMaterials.py")

import Reference

if Reference.PYTHON_DEBUG >= 1:
	execfile("Positions.py")


execfile ("DERR.py")
execfile ("sonidos.py")
execfile ("agua.py")
execfile ("Lavax.py")



execfile ("puertas.py")
execfile ("objs.py")
execfile ("objs-uso.py")
execfile ("rejas.py")
execfile ("pociones.py")
execfile ("armas.py")
execfile ("luces.py")
execfile ("fuego.py")


execfile ("BurnSkl.py")
execfile ("demons.py")

execfile ("Demon.py")

execfile ("ELEVATORS.py")

execfile ("Enemigos.py")

execfile ("Glm11.py")
execfile ("Orks3.py")
execfile ("ZONAOSCURA.py")
execfile ("3GOLEMS.py")
execfile ("MINORX.py")

execfile ("iScene.py")
execfile ("DalGurak3Scene.py")
execfile ("Velaskyalf.py")
execfile ("ChungEnd.py")

char.Position = (116085.24, 12233.57, 49133.79)
char.InitPos = 124966 , 13077 , 52814

#Bladex.SetCallCheck(1)
