import Reference
import Bladex
# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 261 Items.

o=Bladex.CreateEntity("NoName25","Lampcolg",-63070.643000,-6880.738000,102240.099000,Reference.ObjType("Lampcolg"))
o.Scale=1.138093
o.Orientation=0.492646,0.501878,0.498014,-0.507347
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.090000,(255,159,53)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("metalo2","Lamparaegipto",-27442.562000,-1532.841000,-8219.326000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.013057,-0.837621,0.013767,0.545923
o.FiresIntensity=[ 50 ]
o.Lights=[ (0.000000,0.095985,(255,168,72)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("metalo1","Lamparaegipto",-21989.141000,-2899.630000,-6976.560000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.292525,0.294411,0.639259,-0.647379
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.599295,0.095985,(255,164,62)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo16","Halcon",-35468.395000,-1710.666000,16072.003000,Reference.ObjType("Halcon"))
o.Scale=2.067570
o.Orientation=0.707110,0.707031,0.006462,-0.007792
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName44","Halcon2",-24675.870000,5692.284000,27017.633000,Reference.ObjType("Halcon2"))
o.Scale=1.000000
o.Orientation=0.006692,0.006789,0.702233,-0.711883
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName60","Palangana",11349.242000,-1198.135000,-7944.586000,Reference.ObjType("Palangana"))
o.Scale=1.361327
o.Orientation=0.483716,0.491693,0.507780,-0.516154
o.FiresIntensity=[ 73 ]
o.Lights=[ (0.000000,0.031250,(255,137,6)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName66","Halcon",-42671.231000,-9180.345000,-31751.322000,Reference.ObjType("Halcon"))
o.Scale=3.987227
o.Orientation=0.506142,0.494140,-0.505784,0.493790
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName67","Skull",-56773.389000,-1106.471000,-13144.941000,Reference.ObjType("Skull"))
o.Scale=1.149474
o.Orientation=0.609250,0.353189,-0.614232,0.356077
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName68","Skull",-56803.270000,-1119.246000,-12624.964000,Reference.ObjType("Skull"))
o.Scale=1.172579
o.Orientation=0.882751,0.464282,-0.069512,0.019000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName73","Lampcolg",6227.949000,-6244.311000,-3546.341000,Reference.ObjType("Lampcolg"))
o.Scale=1.564811
o.Orientation=0.520757,0.502834,-0.496303,0.479222
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.000000,0.050000,(255,150,34)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName74","Cuerda",6208.791000,-7421.637000,-3560.102000,Reference.ObjType("Cuerda"))
o.Scale=0.827740
o.Orientation=0.033058,0.032684,-0.710363,0.702299
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName85","Peanapiedra",-45089.446000,-7381.114000,46400.717000,Reference.ObjType("Peanapiedra"))
o.Scale=3.203323
o.Orientation=0.011209,-0.009959,0.703552,-0.710485
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName86","Peanapiedra",-45204.552000,-7439.457000,37130.413000,Reference.ObjType("Peanapiedra"))
o.Scale=3.203323
o.Orientation=0.006976,0.000581,0.709907,-0.704261
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName94","Halcon",-29628.861000,-8589.612000,-3868.876000,Reference.ObjType("Halcon"))
o.Scale=1.244716
o.Orientation=0.506510,0.510981,-0.488931,0.493247
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName108","Palangana",-49262.228000,-5450.231000,72697.405000,Reference.ObjType("Palangana"))
o.Scale=0.990099
o.Orientation=0.509594,0.511139,-0.496984,0.481723
o.FiresIntensity=[ 0 ]
o.Lights=[ (2.000000,0.060000,(255,137,6)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName109","Palangana",-49332.689000,-5485.700000,69682.995000,Reference.ObjType("Palangana"))
o.Scale=1.232392
o.Orientation=0.495447,0.502058,-0.497900,0.504544
o.FiresIntensity=[ 3 ]
o.Lights=[ (0.178877,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName112","Lampcolg",4829.442000,-7898.800000,8184.513000,Reference.ObjType("Lampcolg"))
o.Scale=1.347849
o.Orientation=0.495658,0.494016,0.505947,-0.504271
o.FiresIntensity=[ 37 ]
o.Lights=[ (0.000000,0.070000,(255,169,74)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName122","Antorcha",-18504.597000,14062.963000,47040.438000,Reference.ObjType("Antorcha"))
o.Scale=1.000000
o.Orientation=0.393427,0.731733,0.263572,-0.490216
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("metalo3","Lamparaegipto",12374.642000,-1401.298000,-28885.555000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.000000,0.050000,(255,154,43)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("metalo4","Lamparaegipto",4096.517000,-290.140000,-28193.694000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.480371,0.356655,0.144266,0.788180
o.FiresIntensity=[ 1 ]
o.Lights=[ (1.000000,0.060000,(255,164,62)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName135","Lamparaegipto",30001.664000,-4440.877000,4082.412000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.917033,0.012354,-0.398616,0.001786
o.FiresIntensity=[ 36 ]
o.Lights=[ (0.000000,0.078967,(230,141,53)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName136","Lamparaegipto",30245.112000,-5703.070000,9898.795000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.090000,(203,146,67)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName140","Hoguera",-47088.252000,-13702.414000,69551.570000,Reference.ObjType("Hoguera"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName146","Antorchaenpared",-33293.958000,3181.673000,-91406.738000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.705384,0.705384,-0.049325,0.049325
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.791807,0.180994,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName147","Antorchaenpared",-57335.563000,2475.202000,-82039.319000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.650895,0.650895,-0.276289,0.276289
o.FiresIntensity=[ 3 ]
o.Lights=[ (8.149648,0.141814,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName159","Arbolseco2",-72336.763000,-13717.463000,-50226.417000,Reference.ObjType("Arbolseco2"))
o.Scale=1.000000
o.Orientation=0.812144,0.568669,0.106921,0.074867
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName160","Arbolseco2",48981.375000,5307.259000,-104705.868000,Reference.ObjType("Arbolseco2"))
o.Scale=1.628348
o.Orientation=0.677988,0.677988,-0.200829,-0.200829
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName161","Arbolseco2",26401.863000,25639.277000,-130122.727000,Reference.ObjType("Arbolseco2"))
o.Scale=1.388690
o.Orientation=0.779630,0.620146,-0.054256,-0.068209
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName162","Arbolseco",25026.944000,10033.885000,-30044.520000,Reference.ObjType("Arbolseco"))
o.Scale=3.573846
o.Orientation=0.695266,0.707080,0.128860,-0.006171
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName163","Arbolseco2",-885.153000,8122.597000,-95686.351000,Reference.ObjType("Arbolseco2"))
o.Scale=1.000000
o.Orientation=0.804104,0.454940,0.188442,0.333071
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName166","Garfio2",4827.292000,-8729.239000,8196.678000,Reference.ObjType("Garfio2"))
o.Scale=1.126825
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName167","LamparaAurelio",41615.267000,-8656.278000,2598.305000,Reference.ObjType("LamparaAurelio"))
o.Scale=0.869963
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.116130,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName168","Garfio2",41608.773000,-9635.598000,2588.527000,Reference.ObjType("Garfio2"))
o.Scale=1.388690
o.Orientation=0.482246,0.482246,-0.517145,0.517145
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName177","Garfio2",-63079.652000,-7674.791000,102238.120000,Reference.ObjType("Garfio2"))
o.Scale=1.257163
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName182","Antorchaenpared",-59750.711000,5167.917000,76165.281000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.468543,0.468543,0.529592,-0.529592
o.FiresIntensity=[ 3 ]
o.Lights=[ (9.434219,0.135060,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName184","Antorchaenpared",-65254.732000,3834.735000,86335.507000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.440184,0.440184,-0.553388,0.553388
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.925258,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName191","Antorchaenpared",-55330.594000,-1051.141000,20344.822000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.098410,0.098410,-0.700225,0.700225
o.FiresIntensity=[ 3 ]
o.Lights=[ (8.149651,0.111115,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName192","LamparaNegra",-14168.161000,-7845.688000,65889.520000,Reference.ObjType("LamparaNegra"))
o.Scale=1.000000
o.Orientation=0.037007,0.037007,-0.706138,0.706138
o.FiresIntensity=[ 30 ]
o.Lights=[ (0.000000,0.070000,(185,194,114)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName193","Antorchaenpared",-71085.386000,8189.069000,64786.958000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.662327,0.662327,-0.247634,0.247634
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.761572,0.141814,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName202","Roca1Aurelio",-1760.573000,19502.062000,67917.653000,Reference.ObjType("Roca1Aurelio"))
o.Scale=1.798710
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName236","CandilAurelio",10370.290000,-6018.864000,75552.588000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.006164,0.006171,-0.707080,0.707080
o.FiresIntensity=[ 3 ]
o.Lights=[ (3.225097,0.060000,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName240","CandilAurelio",-26553.490000,-12330.145000,-26662.380000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.018510,0.018510,0.706864,-0.706864
o.FiresIntensity=[ 25 ]
o.Lights=[ (0.000000,0.100000,(255,165,64)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName241","CandilAurelio",-29748.282000,-3102.544000,-22068.781000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 41 ]
o.Lights=[ (0.000000,0.082915,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName242","CandilAurelio",-19760.215000,-3069.830000,-28310.093000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.477714,0.477714,-0.521334,0.521334
o.FiresIntensity=[ 28 ]
o.Lights=[ (0.000000,0.061873,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName243","LamparaNegra",-44069.664000,-2697.220000,-36196.103000,Reference.ObjType("LamparaNegra"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 35 ]
o.Lights=[ (0.000000,0.242549,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName244","LamparaNegra",-52659.083000,-3076.772000,18105.204000,Reference.ObjType("LamparaNegra"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 32 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName245","LamparaNegra",-63727.705000,-5804.794000,26870.583000,Reference.ObjType("LamparaNegra"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 58 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName249","CandilAurelio",-50344.114000,-752.236000,93452.932000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.000000,0.090000,(255,160,55)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName251","CandilAurelio",-12083.831000,5091.114000,78875.972000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.486740,0.486740,-0.512917,0.512917
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.090000,(214,142,46)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName255","Lampcolg",-48134.570000,-10600.702000,89354.875000,Reference.ObjType("Lampcolg"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.253335,0.031250,(255,146,26)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo8","Roca1Aurelio",-39710.219000,6425.205000,-83402.439000,Reference.ObjType("Roca1Aurelio"))
o.Scale=1.745810
o.Orientation=0.766044,0.642788,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName258","Varillaancha",-48122.121000,-11023.858000,89368.954000,Reference.ObjType("Varillaancha"))
o.Scale=0.572800
o.Orientation=0.624338,0.624338,-0.331967,0.331967
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName259","Varillaancha",-48152.194000,-11023.319000,89346.433000,Reference.ObjType("Varillaancha"))
o.Scale=0.561514
o.Orientation=0.624338,0.624338,0.331967,-0.331967
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName261","CandilAurelio",-28746.406000,-9582.669000,-2443.183000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.030844,0.030844,0.706434,-0.706434
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName262","CandilAurelio",-51807.174000,-3408.911000,-20141.132000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 30 ]
o.Lights=[ (0.000000,0.040000,(191,142,51)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName263","CandilAurelio",-51805.312000,-2763.658000,-7335.006000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 32 ]
o.Lights=[ (0.000000,0.070000,(197,142,16)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName264","CandilAurelio",3170.486000,-3261.558000,-9878.694000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.525483,0.525483,-0.473147,0.473147
o.FiresIntensity=[ 3 ]
o.Lights=[ (2.078927,0.082915,(255,165,64)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName265","CandilAurelio",-19922.527000,-2739.909000,-51060.225000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.512917,0.512917,0.486740,-0.486740
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.036176,(220,173,86)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName266","LamparaNegra",-48090.150000,-2940.654000,-19478.572000,Reference.ObjType("LamparaNegra"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 33 ]
o.Lights=[ (0.000000,0.122504,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName267","CandilAurelio",-28418.430000,-2722.456000,-51060.786000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.049999,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName297","CandilAurelio",-65891.552000,-6231.891000,86519.925000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.043168,0.043168,-0.705788,0.705788
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.035000,(255,164,62)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName307","Roca1Aurelio",-62081.060000,18743.395000,5526.269000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.067570
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo38","Tronoliso",-24240.461000,-2200.420000,-8068.089000,Reference.ObjType("Tronoliso"))
o.Scale=1.061520
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo6","Roca2Aurelio",-14112.837000,8629.091000,-135734.721000,Reference.ObjType("Roca2Aurelio"))
o.Scale=2.353088
o.Orientation=0.406597,0.913232,-0.023914,-0.010647
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Rama1",-17283.602000,8722.266000,-138074.857000,Reference.ObjType("Rama1"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Rama2",-17644.474000,8421.703000,-138866.786000,Reference.ObjType("Rama2"))
o.Scale=1.780901
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp273","Rama2",-32583.251000,9447.597000,-141613.058000,Reference.ObjType("Rama2"))
o.Scale=1.596263
o.Orientation=0.410619,0.582745,-0.575667,0.400510
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp274","Rama1",-32531.487000,9052.371000,-141206.570000,Reference.ObjType("Rama1"))
o.Scale=1.000000
o.Orientation=0.466454,0.877272,-0.099953,-0.053146
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Rama1",-24750.176000,8812.978000,-142742.228000,Reference.ObjType("Rama1"))
o.Scale=1.564811
o.Orientation=0.055479,0.055479,0.704927,-0.704927
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Rama2",-56653.812000,9999.747000,-62075.551000,Reference.ObjType("Rama2"))
o.Scale=1.834864
o.Orientation=0.492405,0.870323,0.004297,-0.007595
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Rama1",-54965.194000,9398.342000,-61741.564000,Reference.ObjType("Rama1"))
o.Scale=1.459527
o.Orientation=0.250380,0.968148,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Roca1Aurelio",-49379.165000,13731.687000,-62083.641000,Reference.ObjType("Roca1Aurelio"))
o.Scale=1.780901
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo18","Halcon",-412.783000,-3378.578000,-30474.115000,Reference.ObjType("Halcon"))
o.Scale=2.522829
o.Orientation=0.495618,0.495618,0.504344,-0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp290","Halcon",-6103.772000,-14145.997000,38968.857000,Reference.ObjType("Halcon"))
o.Scale=3.831647
o.Orientation=0.508650,0.508650,-0.491198,0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp297","Antorchaenpared",-87253.228000,6580.409000,7413.726000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.428485,0.432401,-0.555112,0.566816
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(205,164,37)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp312","CandilAurelio",-3706.730000,-6035.550000,104617.498000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.504344,0.504344,0.495618,-0.495618
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.065000,(255,137,6)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp315","CandilAurelio",-40405.158000,-6082.539000,104627.021000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.468543,0.468543,0.529592,-0.529592
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.060000,(217,132,47)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo35","Halcon2",-40264.234000,-4981.149000,124230.906000,Reference.ObjType("Halcon2"))
o.Scale=1.257163
o.Orientation=0.504344,0.504344,0.495618,-0.495618
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo34","Halcon2",-48675.791000,-4980.445000,124277.550000,Reference.ObjType("Halcon2"))
o.Scale=1.244716
o.Orientation=0.504344,0.504344,-0.495618,0.495618
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp320","Brasero1",-44657.383000,-3054.907000,128035.394000,Reference.ObjType("Brasero1"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.060000,(215,113,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp323","CandilAurelio",-23615.160000,-7047.122000,109945.114000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.477714,0.477714,-0.521334,0.521334
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.070000,(255,141,15)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp326","CandilAurelio",9676.316000,-5886.141000,103343.158000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.061628,0.061628,-0.704416,0.704416
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.090000,(255,163,60)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("antorchaen9","Antorchaenpared",19880.443000,-4894.375000,74943.687000,Reference.ObjType("Antorchaenpared"))
o.Scale=0.923483
o.Orientation=0.504344,0.495618,0.495618,-0.504344
o.FiresIntensity=[ 39 ]
o.Lights=[ (0.000000,0.050000,(100,81,36)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("antorchaen10","Antorchaenpared",19880.271000,-5122.144000,98888.359000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 35 ]
o.Lights=[ (0.000000,0.040000,(104,71,28)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp338","Palangana",-5448.953000,-5943.814000,88722.077000,Reference.ObjType("Palangana"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.031250,(255,156,47)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp341","Antorchaenpared",-9088.043000,-13177.631000,84700.804000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.495618,0.495618,-0.504344,0.504344
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp344","Vigaro1",-11425.455000,-10367.454000,87320.867000,Reference.ObjType("Vigaro1"))
o.Scale=0.671653
o.Orientation=0.411044,0.632953,-0.357315,0.550217
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp345","Viga",-18622.585000,-10414.851000,87065.578000,Reference.ObjType("Viga"))
o.Scale=2.814640
o.Orientation=0.487579,0.511222,-0.477527,0.522385
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp346","Vigaro2",-18640.084000,-9154.927000,89121.355000,Reference.ObjType("Vigaro2"))
o.Scale=1.000000
o.Orientation=0.050669,-0.966821,-0.250037,-0.013104
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero5","Vigaro2",-19223.427000,-6141.276000,89524.186000,Reference.ObjType("Vigaro2"))
o.Scale=1.020100
o.Orientation=0.869164,0.129897,0.471918,-0.070529
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero4","Vigaro2",-12402.605000,-4510.397000,93191.833000,Reference.ObjType("Vigaro2"))
o.Scale=0.795442
o.Orientation=0.736761,0.632832,0.152191,-0.183152
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp349","Viga",-12124.716000,-9785.982000,89315.963000,Reference.ObjType("Viga"))
o.Scale=2.151522
o.Orientation=0.516232,0.464817,0.534574,-0.481332
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp350","Vigaro1",-17943.005000,-11280.015000,89026.699000,Reference.ObjType("Vigaro1"))
o.Scale=0.720103
o.Orientation=0.483182,0.443428,0.571207,-0.493588
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp351","Viga",-45293.574000,-11394.069000,77174.870000,Reference.ObjType("Viga"))
o.Scale=2.522829
o.Orientation=0.000000,0.000000,0.707107,-0.707107
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp352","Viga",-45208.283000,-11416.709000,84230.380000,Reference.ObjType("Viga"))
o.Scale=2.497850
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp353","Viga",-47014.369000,-11414.086000,84315.391000,Reference.ObjType("Viga"))
o.Scale=2.497850
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp354","Viga",-47187.988000,-11474.552000,77134.511000,Reference.ObjType("Viga"))
o.Scale=2.497850
o.Orientation=0.000000,0.000000,0.707107,-0.707107
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp355","Antorchaenpared",-3567.892000,-10891.610000,93534.689000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.491198,0.491198,0.508650,-0.508650
o.FiresIntensity=[ 0 ]
o.Lights=[ (6.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp358","Lamparaegipto",-29896.979000,-6206.065000,92018.680000,Reference.ObjType("Lamparaegipto"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.066000,(99,120,135)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp361","Antorchaenpared",-75724.193000,1412.678000,134009.283000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.030842,0.030844,-0.706433,0.706434
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.050000,(221,162,51)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo4","Roca1Aurelio",-31341.373000,9599.757000,-132510.732000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.026831
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo5","Roca2Aurelio",-30945.308000,10845.108000,-141098.669000,Reference.ObjType("Roca2Aurelio"))
o.Scale=1.853212
o.Orientation=0.521334,-0.449775,0.545621,0.477714
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp366","Roca1Aurelio",-8803.060000,-6683.390000,-135625.565000,Reference.ObjType("Roca1Aurelio"))
o.Scale=4.190616
o.Orientation=0.173648,0.984808,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo7","Roca1Aurelio",-7350.384000,6525.609000,-130580.569000,Reference.ObjType("Roca1Aurelio"))
o.Scale=2.329790
o.Orientation=0.095231,-0.601267,0.041521,-0.792266
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo3","Roca1Aurelio",-53170.408000,9891.945000,-134250.078000,Reference.ObjType("Roca1Aurelio"))
o.Scale=1.612226
o.Orientation=0.414693,0.909961,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo1","Halcon2",-41679.624000,4528.325000,-109346.411000,Reference.ObjType("Halcon2"))
o.Scale=1.334504
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp390","Adoquinpulsador",-30036.569000,28.401000,9186.935000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.151522
o.Orientation=0.990198,0.097416,0.090773,0.042179
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp391","Adoquinpulsador",-31865.802000,103.830000,7364.473000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.216715
o.Orientation=0.606045,0.714288,0.225736,-0.267481
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp392","Adoquinpulsador",-71931.126000,-6247.098000,38824.100000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.333391
o.Orientation=0.488128,0.448066,-0.505634,0.552541
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp393","Adoquinpulsador",-72515.671000,-7964.825000,37434.936000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.869963
o.Orientation=0.521334,0.521334,-0.477714,0.477714
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo37","Adoquinpulsador",-68555.490000,-2250.851000,37556.503000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.899927
o.Orientation=0.052025,0.595349,0.155367,0.786584
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo9","Adoquinpulsador",-70831.046000,4716.361000,-57602.381000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.538461
o.Orientation=0.683013,0.683013,-0.183013,0.183013
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp396","Adoquinpulsador",-1942.364000,1140.718000,-50989.907000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.987227
o.Orientation=0.575667,0.575667,-0.410619,0.410619
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp397","Adoquinpulsador",-18053.613000,-44.528000,1762.725000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.704814
o.Orientation=0.115380,-0.820969,-0.077825,-0.553751
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo17","Adoquinpulsador",-20276.571000,-1052.246000,-686.086000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.047852
o.Orientation=0.012342,0.012341,-0.706999,0.706999
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp404","Adoquinpulsador",16652.804000,-1612.523000,-4594.875000,Reference.ObjType("Adoquinpulsador"))
o.Scale=6.177481
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp405","Adoquinpulsador",-6311.624000,-3650.764000,28280.126000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.908663
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo2","Adoquinpulsador",-38635.398000,8881.203000,-131253.365000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.329790
o.Orientation=0.558949,0.774561,-0.241537,0.171146
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp407","Adoquinpulsador",-38301.650000,10359.584000,-133800.730000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.947745
o.Orientation=0.752392,0.609275,-0.194582,0.157569
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("antorchaen1","Antorchaenpared",-66021.180000,-5082.562000,73776.827000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (4.000000,0.060000,(225,156,64)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo27","Adoquinpulsador",-12225.228000,-3652.972000,113654.258000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.017675
o.Orientation=0.495618,0.495618,-0.504344,0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo28","Adoquinpulsador",-4267.193000,-2939.703000,116847.390000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.067570
o.Orientation=0.618450,0.618450,-0.342812,0.342812
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero7","Tabla_xl",-3325.115000,-3340.404000,116173.354000,Reference.ObjType("Tabla_xl"))
o.Scale=1.503752
o.Orientation=0.651429,0.749782,0.079356,0.084673
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero6","Tabla_xl",-204.852000,-4102.471000,113519.626000,Reference.ObjType("Tabla_xl"))
o.Scale=1.533978
o.Orientation=0.702498,0.082384,-0.091238,0.700989
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName26","Tabla_rota",-1079.187000,-3052.378000,117796.318000,Reference.ObjType("Tabla_rota"))
o.Scale=1.347849
o.Orientation=0.610175,0.607825,-0.360020,0.358637
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero8","Tabla_xl",-21546.044000,-4028.811000,121595.428000,Reference.ObjType("Tabla_xl"))
o.Scale=1.416603
o.Orientation=0.702324,0.066013,-0.080829,0.704166
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp466","Tabla_xl",-19347.209000,-3056.570000,124030.450000,Reference.ObjType("Tabla_xl"))
o.Scale=1.282432
o.Orientation=0.648459,0.648459,0.281958,-0.281958
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp467","Adoquinpulsador",-36093.347000,-3687.416000,127441.499000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.704814
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp468","Piedra_09",-17135.704000,-3183.205000,124968.488000,Reference.ObjType("Piedra_09"))
o.Scale=1.000000
o.Orientation=0.226666,-0.964477,-0.126061,0.050144
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName33","Piedra_09",-11883.541000,-3184.819000,130465.438000,Reference.ObjType("Piedra_09"))
o.Scale=1.000000
o.Orientation=0.258560,-0.949077,-0.123313,0.131126
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName34","Piedra_01",-12516.022000,-3090.532000,131367.484000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.977961,-0.113300,-0.112346,0.134664
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo33","Adoquinpulsador",-25756.637000,-2954.561000,113377.444000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.816697
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo32","Adoquinpulsador",-27080.085000,-2958.030000,113787.943000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.816697
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp473","Adoquinpulsador",-25730.979000,-2728.480000,114245.896000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.816697
o.Orientation=0.706138,0.706138,0.037007,0.037007
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp474","Tabla_rota",-18162.639000,-4266.107000,87581.491000,Reference.ObjType("Tabla_rota"))
o.Scale=1.871744
o.Orientation=0.593030,0.593030,0.385118,-0.385118
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp475","Tabla_rota",-16444.826000,-4432.256000,85217.984000,Reference.ObjType("Tabla_rota"))
o.Scale=1.232392
o.Orientation=0.652868,0.511719,-0.339717,0.443283
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero3","Tabla_xl",-12285.904000,-4723.680000,91610.093000,Reference.ObjType("Tabla_xl"))
o.Scale=1.694466
o.Orientation=0.552620,0.657126,0.463858,-0.218249
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName42","Tabla_xl",-12939.859000,-4254.825000,86588.808000,Reference.ObjType("Tabla_xl"))
o.Scale=1.295256
o.Orientation=0.660141,0.660141,-0.253404,0.253404
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName43","Adoquinpulsador",-42612.487000,-13980.918000,93524.496000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.871214
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo36","Adoquinpulsador",-42618.562000,-4751.123000,93839.731000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.538461
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja6","Reja",-23162.799000,10608.469000,35009.743000,Reference.ObjType("Reja"))
o.Scale=2.573538
o.Orientation=0.012231,-0.700803,0.012448,-0.713142
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("reja1","Reja",-24099.062000,-11505.876000,-53007.446000,Reference.ObjType("Reja"))
o.Scale=2.448633
o.Orientation=0.500000,0.500000,0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("barril2","Barril",-50746.589000,1585.245000,93227.816000,Reference.ObjType("Barril"))
o.Scale=1.459527
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("barril3","Barril",-50992.477000,1542.420000,92103.792000,Reference.ObjType("Barril"))
o.Scale=1.564811
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp545","Tabla_rota",-50522.745000,1648.214000,83477.229000,Reference.ObjType("Tabla_rota"))
o.Scale=1.321291
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp546","Tabla_rota",-50954.726000,1837.389000,84288.663000,Reference.ObjType("Tabla_rota"))
o.Scale=1.232392
o.Orientation=0.556702,0.342977,-0.414643,0.632868
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp547","Tabla_rota",-48217.450000,2154.655000,86457.016000,Reference.ObjType("Tabla_rota"))
o.Scale=1.160969
o.Orientation=0.207000,0.206286,-0.676881,0.675596
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp550","Piedra_09",-50777.125000,1998.012000,94603.231000,Reference.ObjType("Piedra_09"))
o.Scale=1.000000
o.Orientation=0.684302,0.728414,0.005594,-0.033351
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp551","Tabla_rota",-48257.137000,-13553.721000,72216.885000,Reference.ObjType("Tabla_rota"))
o.Scale=1.232392
o.Orientation=0.589646,0.589646,-0.390278,0.390278
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp552","Tabla_rota",-48220.946000,-13638.370000,72678.195000,Reference.ObjType("Tabla_rota"))
o.Scale=1.138093
o.Orientation=0.280794,0.239008,-0.656865,0.657692
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero10","Tabla_xl",-48199.754000,-13679.491000,73152.198000,Reference.ObjType("Tabla_xl"))
o.Scale=1.172579
o.Orientation=0.620234,0.554530,-0.345290,0.434259
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName21","Piedra_01",-46105.190000,-13612.655000,70989.463000,Reference.ObjType("Piedra_01"))
o.Scale=0.632728
o.Orientation=0.185170,0.668731,-0.557414,-0.455852
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp555","Piedra_01",-45874.376000,-13592.806000,70503.795000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.980389,-0.079098,-0.143610,0.109352
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName27","TinajaPieza2",-65268.846000,-3364.830000,106051.358000,Reference.ObjType("TinajaPieza2"))
o.Scale=1.000000
o.Orientation=0.968177,0.126584,0.082057,-0.199689
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName28","TinajaPieza4",-64660.631000,-3616.569000,104669.286000,Reference.ObjType("TinajaPieza4"))
o.Scale=1.000000
o.Orientation=0.904617,0.018204,0.324702,-0.275509
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp561","TinajaPieza4",-65542.275000,-4177.537000,107332.830000,Reference.ObjType("TinajaPieza4"))
o.Scale=1.244716
o.Orientation=0.276289,0.276289,-0.650895,0.650895
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp562","TinajaPieza3",-64931.953000,-3372.974000,102599.913000,Reference.ObjType("TinajaPieza3"))
o.Scale=1.000000
o.Orientation=0.277747,0.342573,0.881127,0.170634
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp563","Piedra_01",-63023.504000,-3386.746000,106438.024000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.971134,-0.147561,-0.103518,0.156230
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp564","Piedra_01",-62573.931000,-3369.740000,104386.301000,Reference.ObjType("Piedra_01"))
o.Scale=0.787566
o.Orientation=0.926792,-0.235505,-0.247897,0.155376
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp565","TinajaPieza2",-60134.652000,-3383.203000,102033.677000,Reference.ObjType("TinajaPieza2"))
o.Scale=1.361327
o.Orientation=0.265530,0.222531,-0.934282,0.084213
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp569","Adoquinpulsador",-2306.453000,-15035.230000,84971.377000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.376619
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp570","Adoquinpulsador",-1755.026000,-15947.749000,89195.189000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.573538
o.Orientation=0.703851,0.703851,0.067773,-0.067773
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp582","Adoquinpulsador",-31774.621000,12275.681000,44760.318000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.203323
o.Orientation=0.706864,0.706864,0.018510,-0.018510
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp585","Adoquinpulsador",-30761.793000,17807.924000,59099.049000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.047852
o.Orientation=0.525483,0.525483,-0.473147,0.473147
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp586","Skull",19195.404000,-4629.557000,75694.844000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.137850,0.339052,-0.090767,-0.926176
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp587","Skull",18792.361000,-4599.777000,75428.971000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.424454,0.581268,0.576890,0.386218
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp588","Skull",18024.130000,-4601.828000,75572.517000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.302207,0.635495,-0.603744,-0.374579
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp589","Skull",22040.843000,-4596.446000,75420.386000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.867257,0.493152,0.066875,0.013919
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp590","Skeleton_Optimiced",18307.882000,-4578.128000,67382.416000,Reference.ObjType("Skeleton_Optimiced"))
o.Scale=1.000000
o.Orientation=0.707712,0.034685,-0.705631,-0.005025
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp591","Skeleton_Optimiced",21319.061000,-4637.641000,67429.064000,Reference.ObjType("Skeleton_Optimiced"))
o.Scale=1.000000
o.Orientation=0.693344,0.042838,-0.719309,-0.005847
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp592","Skeleton_Optimiced",21354.664000,-4635.876000,99509.843000,Reference.ObjType("Skeleton_Optimiced"))
o.Scale=1.000000
o.Orientation=0.713142,0.012448,-0.700803,0.012233
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp593","Skull",17953.717000,-4600.279000,99479.022000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.879288,0.472659,-0.048583,0.032961
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp594","Skull",-69713.557000,-4590.972000,80238.601000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.650387,0.377097,-0.574995,0.322763
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp595","Skeleton_Optimiced",-73104.881000,-4651.751000,80090.479000,Reference.ObjType("Skeleton_Optimiced"))
o.Scale=1.000000
o.Orientation=0.707080,-0.006171,0.707080,-0.006171
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp596","AdoquinRuna",-61983.335000,5318.336000,138946.295000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp597","AdoquinRuna",-62019.501000,5363.210000,144919.192000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp598","AdoquinRuna",-58039.604000,5323.681000,136948.365000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp599","AdoquinRuna",-60012.838000,5382.928000,146931.192000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp600","AdoquinRuna",-68006.994000,5389.165000,140947.832000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp601","AdoquinRuna",-67956.997000,5349.830000,146929.954000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.495618,0.495618,-0.504344,-0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp602","AdoquinRuna",-73977.747000,5390.346000,142948.292000,Reference.ObjType("AdoquinRuna"))
o.Scale=3.793710
o.Orientation=0.500000,0.500000,-0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp606","Antorchaenpared",-50969.796000,719.533000,124291.615000,Reference.ObjType("Antorchaenpared"))
o.Scale=1.000000
o.Orientation=0.030844,0.030844,-0.706434,0.706434
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(255,156,47)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp636","Viga",-26877.064000,-13630.662000,-48265.341000,Reference.ObjType("Viga"))
o.Scale=3.078330
o.Orientation=0.006164,0.006171,0.707080,-0.707080
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("LEDEntity_temp637","Viga",-21415.358000,-13637.236000,-48292.590000,Reference.ObjType("Viga"))
o.Scale=3.017675
o.Orientation=0.000000,0.000000,0.707107,-0.707107
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("armero1","Armero",3226.084000,-10534.972000,7434.562000,Reference.ObjType("Armero"))
o.Scale=1.000000
o.Orientation=0.495618,0.495618,-0.504344,0.504344
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName650","RhinoClub",-3111.891000,6718.947000,6788.037000,Reference.ObjType("RhinoClub"))
o.Scale=1.000000
o.Orientation=0.185469,0.111637,-0.800349,-0.559088
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","CandilAurelio",-45738.203000,-700.423000,82715.632000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.090000,(255,160,55)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","CandilAurelio",2338.421000,-3974.775000,-37994.627000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.707080,0.707080,0.006171,-0.006171
o.FiresIntensity=[ 0 ]
o.Lights=[ (1.000000,0.060000,(255,173,83)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("dantorcha12","Antorcha",-56819.406000,-1077.557000,-6212.553000,Reference.ObjType("Antorcha"))
o.Scale=1.000000
o.Orientation=0.008943,0.998330,0.029012,-0.049150
o.FiresIntensity=[ 42 ]
o.Lights=[ (0.000000,0.080000,(255,147,28)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","CandilAurelio",3048.465000,-5974.475000,14032.230000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.024678,0.024678,-0.706676,0.706676
o.FiresIntensity=[ 0 ]
o.Lights=[ (3.000000,0.080000,(255,142,17)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","CandilAurelio",9486.449000,-6344.480000,17952.357000,Reference.ObjType("CandilAurelio"))
o.Scale=1.000000
o.Orientation=0.049325,0.049325,0.705384,-0.705384
o.FiresIntensity=[ 0 ]
o.Lights=[ (1.000000,0.070000,(255,145,23)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("metalo5","Reja",17430.078000,-5793.984000,15775.395000,Reference.ObjType("Reja"))
o.Scale=2.306723
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo39","Columna",-24097.690000,-543.605000,-10878.815000,Reference.ObjType("Columna"))
o.Scale=2.376619
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo23","Altar",32008.607000,-4758.904000,7012.896000,Reference.ObjType("Altar"))
o.Scale=0.869963
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo24","Halcon2",31910.962000,-6456.909000,7052.464000,Reference.ObjType("Halcon2"))
o.Scale=1.282432
o.Orientation=0.500000,0.500000,0.500000,-0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo26","Adoquinpulsador",-25687.427000,-3273.101000,94690.056000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.625266
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo25","Adoquinpulsador",-27735.177000,-3248.702000,94676.944000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.958215
o.Orientation=0.500000,0.500000,-0.500000,0.500000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Antorcha2",-27436.920000,10993.705000,-16574.972000,Reference.ObjType("Antorcha2"))
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.031250,(255,196,128)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Baldosa_rota",18404.525000,-2953.454000,22728.861000,Reference.ObjType("Baldosa_rota"))
o.Scale=1.244716
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Piedra_03",10123.253000,-4125.783000,15982.529000,Reference.ObjType("Piedra_03"))
o.Scale=1.000000
o.Orientation=0.633338,0.768914,-0.049256,-0.072306
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Adoquinpulsador",12251.892000,-4120.028000,18016.083000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.374941
o.Orientation=0.703233,0.703233,0.073913,0.073913
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo22","Adoquinpulsador",12312.953000,-5292.020000,19482.981000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.261271
o.Orientation=0.430459,0.486740,-0.512917,0.560986
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Adoquinpulsador",11625.197000,-6445.873000,19611.509000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.283884
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Adoquinpulsador",18134.450000,-9310.250000,21594.330000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.549318
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Adoquinpulsador",14479.465000,-3715.185000,20426.833000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.853212
o.Orientation=0.702561,0.702561,0.080047,0.080047
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName7","Adoquinpulsador",13556.198000,-6748.455000,18330.037000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.238882
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Piedra_01",10229.253000,-3825.403000,18091.601000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.933761,-0.255381,-0.031360,0.248771
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Piedra_01",11560.654000,-3859.451000,17359.288000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.198076,0.530447,0.228770,0.791869
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Adoquinpulsador",20165.964000,-3161.792000,20111.159000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.376619
o.Orientation=0.706138,0.706138,-0.037007,-0.037007
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Adoquinpulsador",18921.198000,-3070.368000,30698.706000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.986894
o.Orientation=0.697409,0.697409,-0.116706,-0.116706
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo19","Adoquinpulsador",531.594000,-2415.714000,-40868.003000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.376619
o.Orientation=0.627211,0.512917,-0.326506,0.486740
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName13","Adoquinpulsador",542.837000,-5724.802000,-40926.748000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.548057
o.Orientation=0.698401,0.698401,0.110616,0.110616
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo20","Adoquinpulsador",1932.011000,-4089.734000,-41293.446000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.006763
o.Orientation=0.493028,0.613989,-0.428367,0.443219
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName15","Piedra_01",2118.566000,-474.319000,-38541.988000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.521114,0.137808,-0.213097,-0.814886
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName16","Piedra_01",738.319000,-1084.834000,-39434.093000,Reference.ObjType("Piedra_01"))
o.Scale=1.000000
o.Orientation=0.749958,0.657688,-0.066043,0.025444
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName17","Piedra_09",1682.769000,-259.427000,-37060.970000,Reference.ObjType("Piedra_09"))
o.Scale=1.295256
o.Orientation=0.682372,0.729002,-0.046381,0.027801
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName18","Piedra_09",9822.809000,-4034.744000,18877.725000,Reference.ObjType("Piedra_09"))
o.Scale=1.430769
o.Orientation=0.680807,0.729089,0.031977,-0.062518
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo15","Adoquinpulsador",-60554.194000,627.610000,-17600.534000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.522829
o.Orientation=0.662619,0.739074,-0.093125,-0.077680
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Adoquinpulsador",-59911.873000,-4246.975000,-15442.329000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.651518
o.Orientation=0.692911,0.692912,0.140974,-0.140974
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Adoquinpulsador",-59079.446000,-3087.662000,-15976.637000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.047099
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Adoquinpulsador",-58593.089000,-1915.864000,-14540.470000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.596263
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Adoquinpulsador",-60503.990000,875.239000,-19439.113000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.928460
o.Orientation=0.247634,0.400510,0.662327,-0.582745
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo12","Adoquinpulsador",-63984.780000,-227.927000,-14062.286000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.987227
o.Orientation=0.666963,0.700901,-0.206091,0.146369
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo14","Adoquinpulsador",-63288.208000,-1960.306000,-14422.676000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.434396
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo13","Adoquinpulsador",-66100.896000,-1820.398000,-13834.308000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.573846
o.Orientation=0.425547,0.500000,0.500000,-0.564721
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Adoquinpulsador",-65670.834000,-3810.516000,-13959.344000,Reference.ObjType("Adoquinpulsador"))
o.Scale=4.232522
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName9","Adoquinpulsador",-65015.282000,1373.637000,-18585.441000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.786772
o.Orientation=0.706138,0.706138,-0.037007,-0.037007
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo11","Roca1",-68174.270000,282.660000,-20990.792000,Reference.ObjType("Roca1"))
o.Scale=1.890462
o.Orientation=0.043619,0.999048,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName11","Roca2",-71998.255000,1977.768000,-35693.368000,Reference.ObjType("Roca2"))
o.Scale=2.173037
o.Orientation=0.710655,0.558200,-0.245498,-0.350876
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName12","Adoquinpulsador",-59953.535000,-1846.589000,-15020.342000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.842787
o.Orientation=0.707080,0.707080,-0.006171,-0.006171
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo40","Adoquinpulsador",-37787.759000,209.785000,-30093.715000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.203323
o.Orientation=0.276289,0.183013,0.683013,-0.650895
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Adoquinpulsador",-41911.533000,70.544000,-29386.142000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.366725
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Piedra_09",-37309.534000,693.525000,-34993.438000,Reference.ObjType("Piedra_09"))
o.Scale=1.149474
o.Orientation=0.256659,-0.944324,-0.107203,0.175746
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Adoquinpulsador",-30836.187000,-8486.740000,-33057.335000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.756148
o.Orientation=0.073913,0.073913,0.703233,-0.703233
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName4","Adoquinpulsador",-44836.149000,75.879000,8887.933000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.047852
o.Orientation=0.646458,0.756905,0.062247,0.072882
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName5","Tabla_rota2",-47844.176000,-4291.459000,79677.273000,Reference.ObjType("Tabla_rota2"))
o.Scale=1.947745
o.Orientation=0.468543,-0.575667,-0.529592,0.410619
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName6","Adoquinpulsador",-14142.244000,-16605.588000,134253.774000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.871214
o.Orientation=0.438859,0.429134,-0.523030,0.591343
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo31","Adoquinpulsador",-14112.851000,-3069.331000,130049.392000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.987797
o.Orientation=0.706138,0.706138,-0.037007,-0.037007
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName8","Adoquinpulsador",-7597.394000,-16845.373000,126869.010000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.625266
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo29","Adoquinpulsador",-6672.634000,-2909.577000,128237.488000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.573538
o.Orientation=0.706434,0.706434,-0.030844,-0.030844
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName10","Adoquinpulsador",-19801.413000,-17315.063000,133316.269000,Reference.ObjType("Adoquinpulsador"))
o.Scale=2.473119
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo30","Adoquinpulsador",-9014.180000,-3129.515000,128840.824000,Reference.ObjType("Adoquinpulsador"))
o.Scale=1.909366
o.Orientation=0.579228,0.640856,0.298836,-0.405580
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero9","Tabla_rota",-47827.292000,-4496.955000,84134.299000,Reference.ObjType("Tabla_rota"))
o.Scale=1.816697
o.Orientation=0.521334,0.521334,0.477714,0.477714
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName13","Tabla_rota",-47454.431000,-3965.886000,81994.764000,Reference.ObjType("Tabla_rota"))
o.Scale=1.596263
o.Orientation=0.681390,0.681390,-0.188966,0.188966
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName15","TinajaPieza5",-63918.029000,-3335.392000,102636.653000,Reference.ObjType("TinajaPieza5"))
o.Scale=1.000000
o.Orientation=0.727449,-0.244353,0.010842,-0.641086
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName16","TinajaPieza4",-65162.572000,-3538.511000,100897.863000,Reference.ObjType("TinajaPieza4"))
o.Scale=1.232392
o.Orientation=0.016154,-0.850087,-0.179244,-0.494938
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName17","BarrilPieza4",-46881.832000,1618.573000,83106.473000,Reference.ObjType("BarrilPieza4"))
o.Scale=1.000000
o.Orientation=0.387078,0.588785,0.380910,0.598674
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName18","BarrilPieza4",-46855.177000,1618.491000,82449.294000,Reference.ObjType("BarrilPieza4"))
o.Scale=1.564811
o.Orientation=0.155177,-0.546012,0.820068,-0.072660
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName19","BarrilPieza4",-46218.870000,2091.385000,85324.837000,Reference.ObjType("BarrilPieza4"))
o.Scale=1.518790
o.Orientation=0.416764,0.550816,0.368634,0.622108
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName23","BarrilPieza5",-47942.273000,1654.205000,83492.482000,Reference.ObjType("BarrilPieza5"))
o.Scale=1.459527
o.Orientation=0.005145,-0.005912,-0.708430,-0.705737
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName24","BarrilPieza6",-47903.109000,1636.793000,82482.787000,Reference.ObjType("BarrilPieza6"))
o.Scale=1.612226
o.Orientation=0.000000,0.002433,-0.707064,-0.707145
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName25","Lanzapivotes",-24279.388000,-1066.555000,16393.209000,Reference.ObjType("Lanzapivotes"))
o.Scale=3.503427
o.Orientation=0.999962,-0.008727,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo21","Adoquinpulsador",-12872.485000,463.078000,-39104.356000,Reference.ObjType("Adoquinpulsador"))
o.Scale=3.171607
o.Orientation=0.314711,0.337954,-0.661849,0.590509
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName28","Tabla_xl",-6910.699000,-1560.485000,-10274.384000,Reference.ObjType("Tabla_xl"))
o.Scale=1.628348
o.Orientation=0.670566,0.670566,-0.224368,0.224368
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero2","Tabla_rota",-4798.187000,-586.146000,-7416.453000,Reference.ObjType("Tabla_rota"))
o.Scale=1.269735
o.Orientation=0.675022,0.496805,-0.320464,0.441398
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName30","Tabla_rota",-6910.804000,-357.935000,-7229.487000,Reference.ObjType("Tabla_rota"))
o.Scale=1.474123
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("madero1","Arbolseco2",-72043.858000,-1287.273000,-31611.853000,Reference.ObjType("Arbolseco2"))
o.Scale=1.628348
o.Orientation=0.556891,0.404605,-0.586840,0.426364
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName32","Rama1",-69119.958000,-397.162000,-31239.181000,Reference.ObjType("Rama1"))
o.Scale=2.261271
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName33","Rama1",-68810.984000,-8.012000,-39241.159000,Reference.ObjType("Rama1"))
o.Scale=1.416603
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName34","Rama2",-69454.221000,-62.109000,-40363.238000,Reference.ObjType("Rama2"))
o.Scale=1.928460
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("pedrolo10","Roca1",-69597.022000,1156.950000,-45905.483000,Reference.ObjType("Roca1"))
o.Scale=1.628348
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


