import Sparks

Sparks.SetMetalSparkling("reja1")
Sparks.SetMetalSparkling("reja2")
Sparks.SetMetalSparkling("reja3")
Sparks.SetMetalSparkling("reja4")
Sparks.SetMetalSparkling("reja5")
Sparks.SetMetalSparkling("reja6")
Sparks.SetMetalSparkling("reja7")


Sparks.SetMetalSparkling("metalo1")
Sparks.SetMetalSparkling("metalo2")
Sparks.SetMetalSparkling("metalo3")
Sparks.SetMetalSparkling("metalo4")
Sparks.SetMetalSparkling("metalo5")
Sparks.SetMetalSparkling("metalo6")
Sparks.SetMetalSparkling("metalo7")
Sparks.SetMetalSparkling("metalo8")
Sparks.SetMetalSparkling("metalo9")
Sparks.SetMetalSparkling("metalo10")
Sparks.SetMetalSparkling("metalo11")
Sparks.SetMetalSparkling("metalo12")
Sparks.SetMetalSparkling("metalo13")


Sparks.SetWoodenSparkling("madero1")
Sparks.SetWoodenSparkling("madero2")
Sparks.SetWoodenSparkling("madero3")
Sparks.SetWoodenSparkling("madero4")
Sparks.SetWoodenSparkling("madero5")
#Sparks.SetWoodenSparkling("madero6")
Sparks.SetWoodenSparkling("madero7")
Sparks.SetWoodenSparkling("madero8")
Sparks.SetWoodenSparkling("madero9")
Sparks.SetWoodenSparkling("madero10")
Sparks.SetWoodenSparkling("madero11")
Sparks.SetWoodenSparkling("madero12")
Sparks.SetWoodenSparkling("madero13")
Sparks.SetWoodenSparkling("madero14")


Sparks.SetStoneSparkling("pedrolo1")
Sparks.SetStoneSparkling("pedrolo2")
Sparks.SetStoneSparkling("pedrolo3")
Sparks.SetStoneSparkling("pedrolo4")
Sparks.SetStoneSparkling("pedrolo5")
Sparks.SetStoneSparkling("pedrolo6")
Sparks.SetStoneSparkling("pedrolo7")
Sparks.SetStoneSparkling("pedrolo8")
Sparks.SetStoneSparkling("pedrolo9")
Sparks.SetStoneSparkling("pedrolo10")
Sparks.SetStoneSparkling("pedrolo11")
Sparks.SetStoneSparkling("pedrolo12")
Sparks.SetStoneSparkling("pedrolo13")
Sparks.SetStoneSparkling("pedrolo14")
Sparks.SetStoneSparkling("pedrolo15")
Sparks.SetStoneSparkling("pedrolo16")
Sparks.SetStoneSparkling("pedrolo17")
Sparks.SetStoneSparkling("pedrolo18")
Sparks.SetStoneSparkling("pedrolo19")
Sparks.SetStoneSparkling("pedrolo20")
Sparks.SetStoneSparkling("pedrolo21")
Sparks.SetStoneSparkling("pedrolo22")
Sparks.SetStoneSparkling("pedrolo23")
Sparks.SetStoneSparkling("pedrolo24")
Sparks.SetStoneSparkling("pedrolo25")
Sparks.SetStoneSparkling("pedrolo26")
Sparks.SetStoneSparkling("pedrolo27")
Sparks.SetStoneSparkling("pedrolo28")
Sparks.SetStoneSparkling("pedrolo29")
Sparks.SetStoneSparkling("pedrolo30")
Sparks.SetStoneSparkling("pedrolo31")
Sparks.SetStoneSparkling("pedrolo32")
Sparks.SetStoneSparkling("pedrolo33")
Sparks.SetStoneSparkling("pedrolo34")
Sparks.SetStoneSparkling("pedrolo35")
Sparks.SetStoneSparkling("pedrolo36")
Sparks.SetStoneSparkling("pedrolo37")
Sparks.SetStoneSparkling("pedrolo38")
Sparks.SetStoneSparkling("pedrolo39")
Sparks.SetStoneSparkling("pedrolo40")
Sparks.SetStoneSparkling("pedrolo41")
Sparks.SetStoneSparkling("pedrolo42")
Sparks.SetStoneSparkling("pedrolo43")
Sparks.SetStoneSparkling("pedrolo44")
Sparks.SetStoneSparkling("pedrolo45")
Sparks.SetStoneSparkling("pedrolo46")
Sparks.SetStoneSparkling("pedrolo47")
Sparks.SetStoneSparkling("pedrolo48")
Sparks.SetStoneSparkling("pedrolo49")
Sparks.SetStoneSparkling("pedrolo50")



#Sparks.SetSparkling("rastrillo1")

