import Bladex
import LoadBar

LoadBar.ECTSProgressBar(292,"Blade_progress.jpg")

execfile("../../Scripts/sys_init.py")

Bladex.ReadLevel("mine.lvl")

execfile("../../Scripts/BladeInit.py")


# Item configuration script
# Script generated by LED: Aug  5 1998 19:56:40

execfile("ActorsInit.py")
execfile("DefFuncs.py")
execfile("MusicEvents.py")
execfile ("TextureMaterials.py")

execfile ("sol.py")

execfile ("objs.py")

execfile ("sonidos.py")

execfile ("sonidospuntuales.py")

execfile ("puertmn.py")

execfile ("elevador.py")

execfile ("elevador4.py")

if Reference.PYTHON_DEBUG >= 1:
	execfile("Positions.py")

execfile ("Luces.py")

execfile ("chaos.py")

execfile ("tablilla.py")

execfile ("transp.py")

execfile ("bgates.py")

execfile("deslz.py")

execfile ("musica.py")

char.Position=-50741, -21360, 1396
char.Angle=4.6483