Bladex.LoadSampledAnimation("../../Anm/Sct_cae.BMV","Sct_cae",1,"SectorVolcan")
Bladex.LoadSampledAnimation("../../Anm/Sct_ondula.BMV","Sct_ondula",1,"SectorVolcan")
Bladex.LoadSampledAnimation("../../Anm/Geo_jump.BMV","Geo_jump",1,"Geoda")
Bladex.LoadSampledAnimation("../../Anm/Prs_1_escena01_volcan.BMV","Prs_1_escena01_volcan",1,"Prisoner_4",20)
Bladex.LoadSampledAnimation("../../Anm/Prs_2_escena01_volcan.BMV","Prs_2_escena01_volcan",1,"Prisoner_5",20)
Bladex.LoadSampledAnimation("../../Anm/Prs_3_escena01_volcan.BMV","Prs_3_escena01_volcan",1,"Prisoner_6",20)
Bladex.LoadSampledAnimation("../../Anm/Prs_1gotohell.BMV","Prs_1gotohell",1,"Prisoner_4")
Bladex.LoadSampledAnimation("../../Anm/Prs_2gotohell.BMV","Prs_2gotohell",1,"Prisoner_5")
