import Bladex
import LoadBar
LoadBar.ECTSProgressBar(562,"Blade_progress.jpg")

execfile("../../Scripts/sys_init.py")

Bladex.ReadLevel("volcano.lvl")

execfile("../../Scripts/BladeInit.py")


# Item configuration script
# Script generated by LED: Aug  5 1998 19:56:40

execfile ("DefFuncs.py")
execfile ("MusicEvents.py")
execfile ("ActorsInit.py")

execfile ("TextureMaterials.py")

if Reference.PYTHON_DEBUG >= 1:
	execfile("Positions.py")

execfile ("objs.py")

execfile ("Luces.py")

execfile("Puertvol2.py")

execfile("Enemigos.py")

execfile("tinajas.py")

execfile ("gargolas.py")

execfile("hurryup.py")

execfile("fourlds.py")

execfile("wscene.py")

execfile("elevador.py")

execfile("elevador2.py")

execfile ("sonidos.py")

execfile ("final.py")

execfile("Arania.py")

execfile("arrowPuz.py")

execfile("Lavax.py")

execfile("desprendimientos.py")

execfile ("iscene.py")

execfile ("musica.py")

execfile ("armas.py")

char.Position=87027.1990596, 2115.59558838, 11171.8992518
char.Angle=1.5656065409

# minorx torturadores  char.Position=25022,5736,21346