import pocimac
import Ontake
import Breakings
import Sparks
import Reference

ad11=Bladex.CreateEntity("ad11","Adoquinpulsador",-40643.858506,-7891.856762,37014.361262,"Physic")
ad11.Scale=2.522829
ad11.Orientation=0.495618,0.495618,0.504344,-0.504344
ad11.CastShadows=0
ad11.Alpha = 0
Reference.EntitiesSelectionData["ad11"]=[0,0,""]

ad12=Bladex.CreateEntity("ad12","Adoquinpulsador",-40640.847672,-7909.281759,34675.339991,"Physic")
ad12.Scale=2.473119
ad12.Orientation=0.500000,0.500000,0.500000,-0.500000
ad12.CastShadows=0
ad12.Alpha = 0
Reference.EntitiesSelectionData["ad12"]=[0,0,""]
## pocimas


o=Bladex.CreateEntity("VolcanPower","PowerPotion",34482.641130,-5392.708038,-5098.295399,"Physic")
o.Scale=1.000000
o.Orientation=0.397255,-0.092396,-0.912444,-0.033118
pocimac.CreatePowerPotion("VolcanPower")


o=Bladex.CreateEntity("Volcanpoc100","Pocima100",93859.651687,2677.663924,-15438.269149,"Physic")
o.Scale=1.000000
o.Orientation=0.202278,-0.308034,0.033795,0.929008
pocimac.CreatePotion("Volcanpoc100")


o=Bladex.CreateEntity("Volcanpoc200","Pocima200",-13480.980891,7919.172114,11348.248241,"Physic")
o.Scale=1.000000
o.Orientation=0.111791,-0.993446,-0.021161,-0.010923
pocimac.CreatePotion("Volcanpoc200")




# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


volcancorona=Bladex.CreateEntity("Volcancorona","Corona",-36238.334009,-3498.355498,21414.972868,"Physic")
volcancorona.Scale=1.000
volcancorona.Orientation=0.491198,0.491198,-0.508650,0.508650
ItemTypes.ItemDefaultFuncs (volcancorona)

luz2_PP=Bladex.CreateEntity("luz2_PP","Entity Spot",-36238.334009,-3898.355498,21414.972868)
luz2_PP.Color=134,60,57
luz2_PP.Intensity=2
luz2_PP.Visible=0
volcancorona.Link(luz2_PP)

	
Ontake.AddOnTakeEvent("Volcancorona",BorraLuz)


############VIGAS PLANAS DE PEGA

tabl=Bladex.CreateEntity("vigatrans1","VigaPlana",-6463.512000,-2776.512000,-14106.471000,"Physic")
tabl.Scale=6.557520
tabl.Orientation=0.707107,0.707107,0.000000,0.000000
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans1"]=[0,0,""]

tabl=Bladex.CreateEntity("vigatrans2","VigaPlana",-6148.663000,-2997.690000,-10833.940000,"Physic")
tabl.Scale=7.171863
tabl.Orientation=0.707107,0.707107,0.000000,0.000000
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans2"]=[0,0,""]

tabl=Bladex.CreateEntity("vigatrans3","VigaPlana",23790.797000,-611.303000,36199.107000,"Physic")
tabl.Scale=7.613078
tabl.Orientation=0.707107,0.707107,0.000000,0.000000
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans3"]=[0,0,""]


tabl=Bladex.CreateEntity("vigatrans4","VigaPlana",24320.485000,-823.423000,39092.670000,"Physic")
tabl.Scale=7.316018
tabl.Orientation=0.707107,0.707107,0.000000,0.000000
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans4"]=[0,0,""]

tabl=Bladex.CreateEntity("vigatrans5","VigaPlana",35927.012000,-2959.241000,26550.627000,"Physic")
tabl.Scale=8.326311
tabl.Orientation=0.495618,0.495618,0.504344,-0.504344
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans5"]=[0,0,""]

tabl=Bladex.CreateEntity("vigatrans6","VigaPlana",32621.542000,-3040.918000,26579.553000,"Physic")
tabl.Scale=7.922199
tabl.Orientation=0.500000,0.500000,0.500000,-0.500000
tabl.CastShadows=0
tabl.Alpha = 0
Reference.EntitiesSelectionData["vigatrans6"]=[0,0,""]

# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 254 Items.

o=Bladex.CreateEntity("NoName4","Lamparatecho",39012.617000,-10829.185000,200.647000,"Physic")
o.Scale=2.329790
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (31.947647,0.509561,(240,126,0)) ]



o=Bladex.CreateEntity("NoName7","Lamparatecho",39311.966000,-14419.898000,13921.875000,"Physic")
o.Scale=2.678033
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,1.000000,(255,137,6)) ]



o=Bladex.CreateEntity("NoName8","Polea",40148.667000,-12691.664000,292.064000,"Physic")
o.Scale=3.235356
o.Orientation=0.512917,0.512917,0.486740,-0.486740



o=Bladex.CreateEntity("NoName9","Polea",38187.972000,-10270.084000,10254.869000,"Physic")
o.Scale=1.967222
o.Orientation=0.482246,0.482246,-0.517145,0.517145



o=Bladex.CreateEntity("NoName10","Polea",30580.913000,208.511000,28738.287000,"Physic")
o.Scale=2.067570
o.Orientation=0.582745,0.582745,-0.400510,0.400510



o=Bladex.CreateEntity("NoName11","Lamparatecho",31285.648000,1907.844000,28450.306000,"Physic")
o.Scale=2.573537
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (12.040738,0.300000,(255,134,0)) ]



o=Bladex.CreateEntity("NoName13","Roca2",22307.548000,10283.658000,32720.833000,"Physic")
o.Scale=1.503752
o.Orientation=0.688355,-0.725374,0.000000,0.000000
Sparks.SetStoneSparkling(o.Name)


o=Bladex.CreateEntity("NoName14","Roca2",24055.794000,10754.207000,28570.658000,"Physic")
o.Scale=1.459527
o.Orientation=0.719340,-0.694658,0.000000,0.000000
Sparks.SetStoneSparkling(o.Name)


o=Bladex.CreateEntity("NoName15","Polea",40942.425000,-7319.303000,43098.992000,"Physic")
o.Scale=2.448633
o.Orientation=0.247634,0.247634,-0.662327,0.662327



o=Bladex.CreateEntity("NoName16","Lampcolg",41713.310000,-5452.670000,44016.909000,"Physic")
o.Scale=2.088246
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (16.000000,0.395086,(247,157,36)) ]



o=Bladex.CreateEntity("NoName17","Polea",41437.136000,-2118.781000,33211.916000,"Physic")
o.Scale=2.678033
o.Orientation=0.648459,0.648459,-0.281958,0.281958



o=Bladex.CreateEntity("NoName18","Polea",30364.407000,-10751.442000,13935.647000,"Physic")
o.Scale=2.704814
o.Orientation=0.508650,0.508650,0.491198,-0.491198



o=Bladex.CreateEntity("NoName19","Polea",28440.964000,-12303.940000,-5969.858000,"Physic")
o.Scale=3.366725
o.Orientation=0.304417,0.304417,0.638224,-0.638224



o=Bladex.CreateEntity("NoName29","Lampcolg",32687.559000,-15498.957000,35086.340000,"Physic")
o.Scale=1.871744
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (25.031855,0.531250,(251,136,32)) ]



o=Bladex.CreateEntity("NoName32","Polea",28746.873000,-10645.242000,43272.500000,"Physic")
o.Scale=3.017675
o.Orientation=0.293232,0.293232,0.643440,-0.643440



o=Bladex.CreateEntity("NoName33","Polea",-10782.099000,-1443.469000,31975.983000,"Physic")
o.Scale=3.538461
o.Orientation=0.645974,0.645974,-0.287606,0.287606



o=Bladex.CreateEntity("NoName34","Polea",-23528.571000,-2211.717000,43718.816000,"Physic")
o.Scale=3.538461
o.Orientation=0.264887,0.264887,0.655618,-0.655618



o=Bladex.CreateEntity("NoName35","Lamparatecho",-25207.468000,-57.736000,45042.175000,"Physic")
o.Scale=2.473119
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.253340,0.031250,(185,97,0)) ]



o=Bladex.CreateEntity("NoName39","Peanapiedra",-37563.275000,-14432.012000,16519.822000,"Physic")
o.Scale=2.573538
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName40","Peanapiedra",-38785.583000,-14448.644000,15294.698000,"Physic")
o.Scale=2.651518
o.Orientation=0.468543,0.468543,0.529592,-0.529592



o=Bladex.CreateEntity("NoName41","Polea",-11551.012000,-16005.227000,43720.054000,"Physic")
o.Scale=2.871214
o.Orientation=0.264887,0.264887,-0.655618,0.655618



o=Bladex.CreateEntity("NoName45","Lampcolg",-17193.527000,-16099.524000,11567.116000,"Physic")
o.Scale=1.890462
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.500000,(255,166,68)) ]



o=Bladex.CreateEntity("NoName46","LamparaNegra",-18888.944000,-21471.329000,16394.733000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.412500,(255,165,66)) ]



o=Bladex.CreateEntity("NoName48","LamparaNegra",-26355.098000,-13162.325000,10093.342000,"Physic")
o.Scale=1.000000
o.Orientation=0.012342,0.012341,0.706999,-0.706999
o.FiresIntensity=[ 3 ]
o.Lights=[ (11.467374,0.375207,(196,103,0)) ]



o=Bladex.CreateEntity("NoName51","LamparaNegra",-10551.998000,6126.422000,11207.999000,"Physic")
o.Scale=1.000000
o.Orientation=0.006164,0.006171,0.707080,-0.707080
o.FiresIntensity=[ 3 ]
o.Lights=[ (3.225097,0.312500,(255,145,21)) ]



o=Bladex.CreateEntity("NoName52","LamparaNegra",-10700.992000,5746.800000,16645.392000,"Physic")
o.Scale=1.000000
o.Orientation=0.495618,0.504344,-0.504344,0.495618
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.312500,(255,138,9)) ]



o=Bladex.CreateEntity("NoName53","LamparaNegra",-20937.424000,5865.796000,11148.676000,"Physic")
o.Scale=1.000000
o.Orientation=0.080742,0.079345,0.696404,-0.708666
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.312500,(249,135,32)) ]



o=Bladex.CreateEntity("NoName55","Lamparatecho",-9373.913000,1296.959000,30713.620000,"Physic")
o.Scale=3.171607
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (0.000000,0.031250,(255,160,55)) ]



o=Bladex.CreateEntity("NoName60","Lamparatecho",-11945.271000,-16769.122000,-3487.007000,"Physic")
o.Scale=2.109128
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (22.839802,0.500784,(217,109,13)) ]



o=Bladex.CreateEntity("NoName61","Polea",-12995.091000,-18738.113000,-4737.554000,"Physic")
o.Scale=3.017675
o.Orientation=0.241845,0.241845,-0.664463,0.664463



o=Bladex.CreateEntity("NoName62","LamparaNegra",-12985.686000,-15286.511000,40970.598000,"Physic")
o.Scale=1.010000
o.Orientation=0.315509,0.315509,0.632814,-0.632814
o.FiresIntensity=[ 3 ]
o.Lights=[ (13.938679,0.331250,(255,145,23)) ]



o=Bladex.CreateEntity("NoName63","LamparaNegra",-33834.031000,-4538.387000,30537.870000,"Physic")
o.Scale=1.000000
o.Orientation=0.006164,0.006171,-0.707080,0.707080
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.116130,0.231250,(255,138,9)) ]



o=Bladex.CreateEntity("NoName64","LamparaNegra",73874.904000,-3103.269000,29204.224000,"Physic")
o.Scale=1.000000
o.Orientation=0.049325,0.049325,0.705384,-0.705384
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.000000,0.031250,(232,121,0)) ]



o=Bladex.CreateEntity("NoName65","LamparaNegra",73926.857000,-3190.990000,14181.661000,"Physic")
o.Scale=1.000000
o.Orientation=0.031112,0.030573,0.700242,-0.712572
o.FiresIntensity=[ 3 ]
o.Lights=[ (0.242946,0.031250,(221,88,0)) ]



o=Bladex.CreateEntity("NoName66","LamparaNegra",73902.130000,-3138.628000,9149.028000,"Physic")
o.Scale=1.000000
o.Orientation=0.012342,0.012341,0.706999,-0.706999
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.215502,0.031250,(255,149,32)) ]



o=Bladex.CreateEntity("NoName67","LamparaNegra",73884.689000,-3232.030000,-5828.639000,"Physic")
o.Scale=1.000000
o.Orientation=0.037007,0.037007,0.706138,-0.706138
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.031250,(249,131,0)) ]



o=Bladex.CreateEntity("NoName68","LamparaNegra",36290.243000,-2287.322000,40071.381000,"Physic")
o.Scale=1.000000
o.Orientation=0.599660,0.599660,-0.374710,0.374710
o.FiresIntensity=[ 3 ]
o.Lights=[ (12.642778,0.300000,(255,155,45)) ]



o=Bladex.CreateEntity("NoName70","Antorchaenpared",32219.401000,-2767.020000,-13179.208000,"Physic")
o.Scale=1.000000
o.Orientation=0.122788,0.122788,0.696364,-0.696364
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.431250,(255,138,9)) ]



o=Bladex.CreateEntity("NoName75","Antorchaenpared",2766.046000,-2358.048000,-18989.614000,"Physic")
o.Scale=1.208109
o.Orientation=0.037008,-0.012340,0.706138,-0.706999
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.531250,(255,137,6)) ]



o=Bladex.CreateEntity("NoName78","LamparaNegra",46107.190000,-6540.092000,7089.764000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 21 ]
o.Lights=[ (0.000000,0.031250,(253,133,0)) ]



o=Bladex.CreateEntity("NoName79","LamparaNegra",46100.122000,-6556.212000,16844.812000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (20.000000,0.212500,(255,141,15)) ]



o=Bladex.CreateEntity("NoName80","LamparaNegra",55622.946000,-5683.822000,18323.387000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 16 ]
o.Lights=[ (0.000000,0.031250,(255,140,13)) ]



o=Bladex.CreateEntity("NoName81","LamparaNegra",55613.037000,-5599.060000,5178.596000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.061250,(198,104,0)) ]



o=Bladex.CreateEntity("NoName82","Polea",14706.731000,-4375.478000,-14298.923000,"Physic")
o.Scale=1.928460
o.Orientation=0.504344,0.504344,-0.495618,0.495618



o=Bladex.CreateEntity("NoName83","Lampcolg",15730.499000,-2139.291000,-14335.029000,"Physic")
o.Scale=1.388690
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (19.613091,0.512500,(232,121,0)) ]



o=Bladex.CreateEntity("NoName84","Lampcolg",5819.272000,-14676.191000,-5527.278000,"Physic")
o.Scale=1.321291
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.039983,0.031250,(255,140,13)) ]



o=Bladex.CreateEntity("NoName85","Polea",5300.106000,-15851.543000,-5507.455000,"Physic")
o.Scale=1.269735
o.Orientation=0.504344,0.504344,-0.495618,0.495618



o=Bladex.CreateEntity("NoName86","Polea",11042.174000,-15366.388000,-14551.478000,"Physic")
o.Scale=1.518790
o.Orientation=0.482246,0.482246,0.517145,-0.517145



o=Bladex.CreateEntity("NoName87","Lampcolg",10232.390000,-14253.086000,-14493.973000,"Physic")
o.Scale=1.295256
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (32.813038,0.631250,(255,142,17)) ]



o=Bladex.CreateEntity("NoName88","Antorchaenpared",12732.190000,3277.073000,-11.913000,"Physic")
o.Scale=1.000000
o.Orientation=0.500000,0.500000,-0.500000,0.500000
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.321937,0.231250,(253,133,0)) ]



o=Bladex.CreateEntity("NoName89","Antorchaenpared",3748.579000,3664.840000,-5.320000,"Physic")
o.Scale=1.000000
o.Orientation=0.517145,0.517145,-0.482246,0.482246
o.FiresIntensity=[ 3 ]
o.Lights=[ (9.905948,0.512500,(255,150,34)) ]



o=Bladex.CreateEntity("NoName92","Antorchaenpared",-24017.157000,6282.923000,7017.411000,"Physic")
o.Scale=1.000000
o.Orientation=0.468543,0.468543,0.529592,-0.529592
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.031250,(255,196,128)) ]



o=Bladex.CreateEntity("NoName100","Antorcha",-2955.584000,-9080.163000,13202.444000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (49.561272,0.031250,(187,62,9)) ]



o=Bladex.CreateEntity("NoName102","Polea",11090.588000,-15258.346000,-5418.248000,"Physic")
o.Scale=1.416603
o.Orientation=0.491198,0.491198,0.508650,-0.508650



o=Bladex.CreateEntity("NoName103","LamparaNegra",-29426.330000,461.398000,-14527.060000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.000000,0.331250,(255,138,9)) ]



o=Bladex.CreateEntity("NoName104","LeonBronce",83343.298000,-1921.296000,17265.078000,"Physic")
o.Scale=1.269735
o.Orientation=0.435338,0.435338,-0.557208,0.557208



o=Bladex.CreateEntity("NoName105","LeonBronce",82901.857000,-2035.809000,6223.216000,"Physic")
o.Scale=1.347849
o.Orientation=0.553388,0.553388,-0.440184,0.440184



o=Bladex.CreateEntity("NoName112","Tablatortura",-43206.674000,6894.128000,14344.978000,"Physic")
o.Scale=1.374941
o.Orientation=1.000000,0.000000,0.000000,0.000000
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName113","Antorchaenpared",-39262.152000,5995.188000,11241.052000,"Physic")
o.Scale=1.000000
o.Orientation=0.024683,-0.037008,0.706676,-0.706138
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.431250,(255,145,21)) ]



o=Bladex.CreateEntity("NoName114","Pinchos",-33152.391000,6481.611000,15906.651000,"Physic")
o.Scale=1.000000
o.Orientation=0.508650,0.508650,0.491198,-0.491198



o=Bladex.CreateEntity("NoName120","LamparaNegra",67020.818000,-2927.467000,14130.520000,"Physic")
o.Scale=1.000000
o.Orientation=0.006275,0.006062,-0.694632,0.719312
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.538023,0.212500,(255,146,26)) ]



o=Bladex.CreateEntity("NoName122","Antorchaenpared",-12297.668000,-2330.330000,34901.045000,"Physic")
o.Scale=1.000000
o.Orientation=0.073913,0.147016,-0.703233,0.691655
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.704739,0.300000,(253,133,0)) ]



o=Bladex.CreateEntity("NoName123","Antorchaenpared",-14203.805000,-5874.973000,33060.746000,"Physic")
o.Scale=1.000000
o.Orientation=0.405580,0.405580,-0.579228,0.579228
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.920125,0.031250,(193,102,0)) ]



o=Bladex.CreateEntity("NoName125","Antorchaenpared",-9722.708000,3268.480000,6031.559000,"Physic")
o.Scale=1.000000
o.Orientation=0.482246,0.482246,0.517145,-0.517145
o.FiresIntensity=[ 3 ]
o.Lights=[ (9.000000,0.531250,(236,124,0)) ]



o=Bladex.CreateEntity("NoName127","Antorchaenpared",-13957.851000,-2001.892000,-7870.534000,"Physic")
o.Scale=1.000000
o.Orientation=0.177045,0.104517,0.684584,-0.699340
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.391974,0.031250,(248,125,35)) ]



o=Bladex.CreateEntity("NoName128","LeonBronce",-22044.932000,-6114.675000,-96032.387000,"Physic")
o.Scale=0.811430
o.Orientation=0.454519,0.454519,-0.541675,0.541675



o=Bladex.CreateEntity("NoName129","LeonBronce",-22201.660000,-6116.017000,-105001.288000,"Physic")
o.Scale=0.811430
o.Orientation=0.549525,0.549525,-0.444997,0.444997



o=Bladex.CreateEntity("NoName132","LamparaMiguel",-6537.125000,-7425.089000,-32429.010000,"Physic")
o.Scale=1.308209
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (23.839830,0.031250,(243,103,10)) ]



o=Bladex.CreateEntity("NoName133","LamparaMiguel",17621.504000,-7437.582000,-32600.377000,"Physic")
o.Scale=1.220190
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (13.938662,0.031250,(230,105,13)) ]



o=Bladex.CreateEntity("NoName134","Antorchaenpared",8724.042000,-10371.812000,-43966.643000,"Physic")
o.Scale=1.000000
o.Orientation=0.508650,0.508650,-0.491198,0.491198
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.091250,(249,131,0)) ]



o=Bladex.CreateEntity("NoName135","Antorchaenpared",3209.656000,-10317.541000,-43965.190000,"Physic")
o.Scale=1.000000
o.Orientation=0.517145,0.517145,-0.482246,0.482246
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.131250,(243,122,33)) ]



o=Bladex.CreateEntity("NoName136","GargolaFernando",10889.033000,-7150.012000,-47932.114000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName137","Antorchaenpared",-19593.400000,-10752.305000,32374.281000,"Physic")
o.Scale=1.000000
o.Orientation=0.632814,0.632814,-0.315509,0.315509
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.385466,0.425490,(252,122,35)) ]



o=Bladex.CreateEntity("NoName138","Antorchaenpared",40259.742000,-2338.477000,16069.482000,"Physic")
o.Scale=1.000000
o.Orientation=0.012342,0.012341,-0.706999,0.706999
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.061873,(215,113,0)) ]



o=Bladex.CreateEntity("NoName140","GargolaFernando",39734.915000,-13465.332000,-6622.802000,"Physic")
o.Scale=1.488864
o.Orientation=0.276289,0.276289,-0.650895,0.650895



o=Bladex.CreateEntity("NoName141","Candil",-14543.158000,-10648.931000,-80647.847000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.950822,(255,54,26)) ]



o=Bladex.CreateEntity("NoName143","Candil",-10597.466000,-10566.499000,-107449.217000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (1.000000,0.950822,(255,54,26)) ]



o=Bladex.CreateEntity("NoName148","Antorchaenpared",100505.974000,770.769000,17080.494000,"Physic")
o.Scale=1.138093
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (3.555669,0.031250,(221,116,0)) ]



o=Bladex.CreateEntity("NoName149","Antorchaenpared",100488.299000,759.449000,6275.688000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.000000,0.095985,(255,147,28)) ]



o=Bladex.CreateEntity("NoName150","GargolaFernando",1290.656000,-7470.036000,-47882.850000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName156","Antorchaenpared",36796.806000,181.930000,-26552.527000,"Physic")
o.Scale=1.000000
o.Orientation=0.508650,0.508650,0.491198,-0.491198
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.309560,(202,86,9)) ]



o=Bladex.CreateEntity("NoName159","Jaula",-10471.496000,-12440.201000,45017.972000,"Physic")
o.Scale=1.580459
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName160","Antorchaenpared",-34480.228000,-10885.840000,43083.888000,"Physic")
o.Scale=1.000000
o.Orientation=0.030573,0.031112,0.712572,-0.700242
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.391974,0.378967,(255,147,28)) ]



o=Bladex.CreateEntity("NoName161","Antorchaenpared",32839.858000,-7916.685000,-6432.898000,"Physic")
o.Scale=1.000000
o.Orientation=0.589646,0.589646,0.390278,-0.390278
o.FiresIntensity=[ 3 ]
o.Lights=[ (20.000000,0.311778,(245,129,41)) ]



o=Bladex.CreateEntity("NoName162","Antorchaenpared",-18555.862000,-11877.010000,-17735.355000,"Physic")
o.Scale=1.000000
o.Orientation=0.568413,0.568413,-0.420603,0.420603
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.538033,0.031250,(254,143,44)) ]



o=Bladex.CreateEntity("NoName163","Antorchaenpared",-22773.891000,15.819000,-13778.920000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (5.000000,0.395087,(255,141,15)) ]



o=Bladex.CreateEntity("NoName167","Jaula",26814.917000,-7484.384000,-4785.209000,"Physic")
o.Scale=1.928460
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName172","LamparaMiguelSinPeana",30464.280000,-5071.340000,-85033.850000,"Physic")
o.Scale=1.232392
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (13.274917,0.056120,(255,162,57)) ]



o=Bladex.CreateEntity("NoName173","Antorchaenpared",-16563.149000,-8734.585000,-9841.917000,"Physic")
o.Scale=1.030301
o.Orientation=0.564720,0.630036,-0.425548,0.321020
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.031250,(255,165,66)) ]



o=Bladex.CreateEntity("NoName174","Antorchaenpared",-19289.661000,-5113.678000,-13721.953000,"Physic")
o.Scale=1.000000
o.Orientation=0.287606,0.218508,0.645974,-0.672499
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.031250,(255,147,28)) ]



o=Bladex.CreateEntity("RAS6","Rastrillo",34348.468000,-1953.284000,3959.481000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName179","LamparaNegra",15306.324000,-12485.451000,-88055.427000,"Physic")
o.Scale=1.000000
o.Orientation=0.517145,0.517145,-0.482246,0.482246
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.225100,0.128629,(255,146,26)) ]



o=Bladex.CreateEntity("NoName182","Roca2",25222.912000,9640.687000,25382.011000,"Physic")
o.Scale=1.402577
o.Orientation=0.843391,0.537300,0.000000,0.000000
Sparks.SetStoneSparkling(o.Name)


o=Bladex.CreateEntity("NoName185","Antorchaenpared",-16226.648000,-20248.674000,35451.047000,"Physic")
o.Scale=1.000000
o.Orientation=0.545621,0.545621,0.449775,-0.449775
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.764942,0.457362,(248,113,22)) ]



o=Bladex.CreateEntity("NoName195","Cuerda",26889.756000,-10824.748000,-4689.327000,"Physic")
o.Scale=1.711410
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName196","Cuerda",-10419.215000,-15039.079000,44963.937000,"Physic")
o.Scale=1.374941
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName197","Palangana",-45037.886000,-8736.563000,43793.463000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.000000,0.262500,(245,150,80)) ]



o=Bladex.CreateEntity("NoName199","Varillaancha",-17247.154000,-16828.103000,11574.186000,"Physic")
o.Scale=1.321291
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName200","Cuerda",15729.289000,-3721.540000,-14338.225000,"Physic")
o.Scale=1.361327
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Varillaancha",32543.411000,-16172.502000,34919.835000,"Physic")
o.Scale=1.220190
o.Orientation=0.648459,0.648459,-0.281958,0.281958



o=Bladex.CreateEntity("NoName0","Antorchaenpared",37065.473000,7737.795000,40215.979000,"Physic")
o.Scale=1.051010
o.Orientation=0.690346,0.690346,-0.153046,0.153046
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.031250,(197,88,7)) ]



o=Bladex.CreateEntity("NoName1","Lampcolg",-56795.570000,1713.424000,25470.257000,"Physic")
o.Scale=1.445076
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.031250,(255,196,128)) ]



o=Bladex.CreateEntity("NoName2","Varillaancha",-56778.376000,1194.100000,25478.697000,"Physic")
o.Scale=2.238882
o.Orientation=0.482246,0.482246,0.517145,-0.517145



o=Bladex.CreateEntity("NoName3","Antorchaenpared",-33022.717000,-10404.313000,38773.280000,"Physic")
o.Scale=1.000000
o.Orientation=0.504344,0.504344,0.495618,-0.495618
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.231250,(251,136,60)) ]



o=Bladex.CreateEntity("NoName0","Cuerda",41730.638000,-7008.092000,44027.250000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-43318.559000,-13460.483000,11827.029000,"Physic")
o.Scale=1.000000
o.Orientation=0.030844,0.030844,-0.706434,0.706434
o.FiresIntensity=[ 3 ]
o.Lights=[ (6.000000,0.031250,(158,73,10)) ]



o=Bladex.CreateEntity("RAS11","Rastrillo",-4370.826000,-11918.152000,10308.002000,"Physic")
o.Scale=1.000000
o.Orientation=0.500000,0.500000,0.500000,-0.500000



o=Bladex.CreateEntity("NoName0","Cuerda",5832.758000,-15465.232000,-5530.753000,"Physic")
o.Scale=0.404348
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName1","Cuerda",10229.632000,-15183.181000,-14500.100000,"Physic")
o.Scale=0.602019
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-16704.584000,-17875.056000,-14719.016000,"Physic")
o.Scale=1.000000
o.Orientation=0.395409,0.395409,0.586218,-0.586218
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.000000,0.312500,(255,183,102)) ]



o=Bladex.CreateEntity("NoName3","LamparaNegra",-44532.960000,1424.466000,-14221.462000,"Physic")
o.Scale=1.000000
o.Orientation=0.504344,0.504344,-0.495618,0.495618
o.FiresIntensity=[ 3 ]
o.Lights=[ (20.000000,0.531250,(245,97,7)) ]



o=Bladex.CreateEntity("NoName4","LamparaNegra",-49775.975000,6024.161000,-27018.489000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.331250,(255,141,15)) ]



o=Bladex.CreateEntity("NoName0","LamparaNegra",2834.411000,-8977.628000,-91860.370000,"Physic")
o.Scale=1.000000
o.Orientation=0.706999,0.706999,0.012341,-0.012341
o.FiresIntensity=[ 10 ]
o.Lights=[ (30.000000,0.500000,(238,139,6)) ]



o=Bladex.CreateEntity("NoName1","LamparaNegra",19475.020000,-11010.346000,-109649.526000,"Physic")
o.Scale=1.000000
o.Orientation=0.537688,0.537688,0.459229,-0.459229
o.FiresIntensity=[ 3 ]
o.Lights=[ (7.000000,0.031250,(255,54,26)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",40030.244000,-12483.127000,-10351.799000,"Physic")
o.Scale=1.160969
o.Orientation=0.165070,0.092296,0.687569,-0.701057
o.FiresIntensity=[ 3 ]
o.Lights=[ (20.000000,0.312500,(225,132,6)) ]



o=Bladex.CreateEntity("NoName1","Antorchaenpared",36583.105000,320.332000,-17637.350000,"Physic")
o.Scale=1.000000
o.Orientation=0.364772,0.539058,-0.583758,0.485370
o.FiresIntensity=[ 3 ]
o.Lights=[ (10.000000,0.312500,(249,135,60)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-45800.748000,-14861.540000,-1996.656000,"Physic")
o.Scale=1.000000
o.Orientation=0.030844,0.030844,-0.706434,0.706434
o.FiresIntensity=[ 3 ]
o.Lights=[ (18.429146,0.031250,(244,129,0)) ]



o=Bladex.CreateEntity("NoName1","Antorchaenpared",-32755.028000,-14316.977000,-10224.466000,"Physic")
o.Scale=1.000000
o.Orientation=0.495618,0.495618,0.504344,-0.504344
o.FiresIntensity=[ 3 ]
o.Lights=[ (4.000000,0.031250,(250,135,31)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",75880.201000,-12104.418000,58921.624000,"Physic")
o.Scale=1.000000
o.Orientation=0.557208,0.557208,-0.435338,0.435338
o.FiresIntensity=[ 3 ]
o.Lights=[ (20.000000,0.031250,(226,251,252)) ]



o=Bladex.CreateEntity("NoName0","Reja",578.741000,8082.065000,34866.443000,"Physic")
o.Scale=1.745810
o.Orientation=0.999962,0.008727,0.000000,0.000000



o=Bladex.CreateEntity("NoName1","Reja",575.402000,8088.854000,42361.841000,"Physic")
o.Scale=1.402577
o.Orientation=1.000000,0.000000,0.000000,0.000000



o=Bladex.CreateEntity("NoName3","Vigaro1",7304.125000,3315.022000,45356.211000,"Physic")
o.Scale=1.000000
o.Orientation=0.909961,0.414694,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Lamparatecho",28918.317000,-9033.636000,13893.249000,"Physic")
o.Scale=2.548057
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (30.000000,0.412500,(255,157,49)) ]



o=Bladex.CreateEntity("NoName0","Vigaro1",4501.518000,4025.496000,45638.762000,"Physic")
o.Scale=1.000000
o.Orientation=0.958820,0.284015,0.000000,0.000000



o=Bladex.CreateEntity("NoName1","Vigaro1",12747.205000,3603.536000,36713.791000,"Physic")
o.Scale=1.000000
o.Orientation=0.874620,0.484810,0.000000,0.000000



o=Bladex.CreateEntity("NoName2","Vigaro1",17050.167000,3392.380000,39737.200000,"Physic")
o.Scale=1.000000
o.Orientation=0.894934,-0.446198,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Roca1",268.419000,9227.316000,55499.775000,"Physic")
o.Scale=1.816697
o.Orientation=0.857167,0.515038,0.000000,0.000000
Sparks.SetStoneSparkling(o.Name)


o=Bladex.CreateEntity("NoName2","Lampcolg",9646.326000,-1695.826000,30600.051000,"Physic")
o.Scale=1.308209
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 3 ]
o.Lights=[ (15.000000,0.400000,(255,142,17)) ]



o=Bladex.CreateEntity("NoName3","Polea",9685.819000,-3601.857000,29321.919000,"Physic")
o.Scale=2.238882
o.Orientation=0.012342,0.012341,0.706999,-0.706999



o=Bladex.CreateEntity("NoName0","Cuerda",9650.070000,-2967.322000,30608.474000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName0","Monjespada",22049.074000,-8910.609000,12015.289000,"Physic")
o.Scale=4.675337
o.Orientation=0.491198,0.491198,-0.508650,0.508650



o=Bladex.CreateEntity("NoName1","Antorchaenpared",-10124.983000,2709.976000,15546.745000,"Physic")
o.Scale=1.000000
o.Orientation=0.449775,0.449775,0.545621,-0.545621
o.FiresIntensity=[ 0 ]
o.Lights=[ (11.000000,0.531250,(255,142,17)) ]



o=Bladex.CreateEntity("NoName2","Peanapiedra",10292.380000,5903.676000,44359.854000,"Physic")
o.Scale=9.570880
o.Orientation=0.030844,0.030844,0.706434,-0.706434



o=Bladex.CreateEntity("NoName3","Peanapiedra",1313.151000,6422.359000,44462.228000,"Physic")
o.Scale=11.222609
o.Orientation=0.706676,0.706676,0.024678,-0.024678



o=Bladex.CreateEntity("NoName4","Peanapiedra",13275.193000,5806.499000,51386.773000,"Physic")
o.Scale=9.959496
o.Orientation=0.024678,0.024678,-0.706676,0.706676



o=Bladex.CreateEntity("NoName5","Peanapiedra",794.671000,5594.106000,51471.457000,"Physic")
o.Scale=7.689208
o.Orientation=0.704416,0.704416,-0.061628,0.061628



o=Bladex.CreateEntity("NoName3","Lampcolg",55156.885000,-1394.444000,-28037.571000,"Physic")
o.Scale=1.503752
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(216,55,1)) ]



o=Bladex.CreateEntity("NoName0","Varillaancha",55371.754000,-1914.956000,-26495.259000,"Physic")
o.Scale=1.115668
o.Orientation=0.473147,0.473147,0.525483,-0.525483



o=Bladex.CreateEntity("NoName1","Antorchaenpared",40900.724000,6592.029000,23838.080000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.512500,(234,123,0)) ]



o=Bladex.CreateEntity("NoName1","Antorchaenpared",35656.896000,-10560.005000,-30131.235000,"Physic")
o.Scale=1.000000
o.Orientation=0.006164,0.006171,0.707080,-0.707080
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.031250,(255,134,0)) ]



o=Bladex.CreateEntity("NoName18","Cuerda",3645.693000,-5060.840000,11350.180000,"Physic")
o.Scale=2.678033
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName19","Lamparatecho",3645.693000,-2980.840000,11350.180000,"Physic")
o.Scale=2.678033
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (0.000000,0.531250,(255,141,15)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-23280.090000,6793.661000,5999.392000,"Physic")
o.Scale=1.126825
o.Orientation=0.420603,0.420603,0.568413,-0.568413
o.FiresIntensity=[ 0 ]
o.Lights=[ (4.000000,0.312500,(255,136,4)) ]



o=Bladex.CreateEntity("NoName1","Antorchaenpared",16695.590000,146.578000,40133.427000,"Physic")
o.Scale=1.072135
o.Orientation=0.517145,0.517145,0.482246,-0.482246
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.312500,(234,123,0)) ]



o=Bladex.CreateEntity("NoName3","Garfio",16626.036000,-16717.055000,37763.963000,"Physic")
o.Scale=1.149474
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName4","Lampcolg",16605.939000,-15894.519000,37789.916000,"Physic")
o.Scale=1.388690
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 8 ]
o.Lights=[ (6.000000,0.331250,(240,126,0)) ]



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-71279.956000,9134.182000,-21494.938000,"Physic")
o.Scale=1.334504
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (30.000000,0.531250,(236,124,0)) ]



o=Bladex.CreateEntity("LAMPEG3","Lamparaegipto",31554.639000,-5716.750000,-100547.478000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (30.000000,0.800000,(255,142,17)) ]



o=Bladex.CreateEntity("LAMPEG1","Lamparaegipto",-15037.024000,-5738.048000,-104955.143000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (5.000000,1.000000,(251,132,0)) ]



o=Bladex.CreateEntity("LAMPEG2","Lamparaegipto",-14968.608000,-5709.499000,-96266.604000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (40.000000,0.531250,(255,140,13)) ]



o=Bladex.CreateEntity("NoName0","Baldosa_01",-14702.001000,9790.496000,645.166000,"Physic")
o.Scale=3.078330
o.Orientation=0.684584,0.703851,0.067773,-0.177045



o=Bladex.CreateEntity("NoName1","Baldosa_01",-13137.566000,9450.488000,-37.961000,"Physic")
o.Scale=1.909366
o.Orientation=0.690346,0.706434,-0.153046,0.030844



o=Bladex.CreateEntity("NoName2","Baldosa_01",-16427.580000,9303.590000,-5033.779000,"Physic")
o.Scale=1.909366
o.Orientation=0.730701,0.657926,0.135427,-0.121939



o=Bladex.CreateEntity("NoName3","Baldosa_01",-18154.015000,9351.040000,-4876.802000,"Physic")
o.Scale=2.329790
o.Orientation=0.736979,0.611403,-0.183940,0.221843



o=Bladex.CreateEntity("NoName4","Lampcolg",-17335.709000,4572.703000,-11902.721000,"Physic")
o.Scale=1.694466
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 6 ]
o.Lights=[ (5.000000,0.100000,(234,123,0)) ]



o=Bladex.CreateEntity("NoName5","Garfio",-17315.781000,3660.961000,-11907.998000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName10","Antorchaenpared",945.572000,6593.821000,16950.938000,"Physic")
o.Scale=1.000000
o.Orientation=0.486740,0.553388,-0.512917,0.440184
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.312500,(242,128,0)) ]



o=Bladex.CreateEntity("NoName11","Adoquinpulsador",48616.726000,10695.335000,35543.665000,"Physic")
o.Scale=4.232522
o.Orientation=0.706676,0.706676,-0.024678,-0.024678



o=Bladex.CreateEntity("NoName12","Adoquinpulsador",42709.938000,10459.279000,35365.236000,"Physic")
o.Scale=2.871214
o.Orientation=0.706676,0.706676,0.024678,-0.024678



o=Bladex.CreateEntity("NoName13","Adoquinpulsador",47080.119000,10618.991000,37438.041000,"Physic")
o.Scale=3.468740
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName14","Adoquinpulsador",-50797.179000,15013.098000,-17624.314000,"Physic")
o.Scale=4.913826
o.Orientation=0.379928,0.468543,0.596368,-0.529592



o=Bladex.CreateEntity("NoName15","Adoquinpulsador",-53320.436000,14787.376000,-12530.667000,"Physic")
o.Scale=3.718959
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName16","Adoquinpulsador",-65444.096000,14552.126000,-14742.711000,"Physic")
o.Scale=4.404379
o.Orientation=0.595328,0.499540,0.482087,-0.404519



o=Bladex.CreateEntity("NoName17","Adoquinpulsador",-63069.842000,14584.160000,-12862.216000,"Physic")
o.Scale=4.360771
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName18","Adoquinpulsador",-59403.207000,14583.274000,-12832.683000,"Physic")
o.Scale=3.400392
o.Orientation=0.696364,0.696364,0.122788,-0.122788



o=Bladex.CreateEntity("NoName19","Adoquinpulsador",-70630.571000,5034.467000,-24090.771000,"Physic")
o.Scale=3.267710
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName20","Adoquinpulsador",-64446.982000,4601.358000,-24454.148000,"Physic")
o.Scale=2.283884
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName21","Adoquinpulsador",-51817.285000,-4496.508000,-25821.024000,"Physic")
o.Scale=2.731862
o.Orientation=0.500000,0.500000,0.500000,-0.500000



o=Bladex.CreateEntity("NoName23","Baldosa_01",-38258.498000,-2411.339000,28010.380000,"Physic")
o.Scale=2.786772
o.Orientation=0.705384,0.705384,0.049325,0.049325



o=Bladex.CreateEntity("NoName24","Baldosa_01",-34569.652000,-2296.810000,27966.910000,"Physic")
o.Scale=1.834864
o.Orientation=0.691655,0.701836,0.086175,-0.147016



o=Bladex.CreateEntity("NoName0","Lamparatecho",21450.037000,-8639.187000,-17950.254000,"Physic")
o.Scale=3.171607
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (50.000000,0.531250,(232,121,0)) ]



o=Bladex.CreateEntity("NoName1","Polea",20592.443000,-11215.874000,-17980.905000,"Physic")
o.Scale=2.329790
o.Orientation=0.491198,0.491198,-0.508650,0.508650



o=Bladex.CreateEntity("NoName2","Antorchaenpared",53478.594000,4384.145000,-11291.213000,"Physic")
o.Scale=1.000000
o.Orientation=0.706138,0.706138,-0.037007,-0.037007
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.300000,(234,123,0)) ]



o=Bladex.CreateEntity("NoName8","Femur",-48741.299813,14679.782549,-26657.546807,Reference.ObjType("Femur"))
o.Scale=1.000000
o.Orientation=0.148814,-0.156955,0.024249,-0.976028



o=Bladex.CreateEntity("NoName9","Femur",-48701.974101,14646.837211,-25659.110428,Reference.ObjType("Femur"))
o.Scale=1.000000
o.Orientation=0.677344,0.138534,-0.718711,-0.073941



o=Bladex.CreateEntity("NoName10","Femur",-48774.706783,14672.234558,-27342.168995,Reference.ObjType("Femur"))
o.Scale=1.000000
o.Orientation=0.030963,0.389710,0.058427,-0.918560



o=Bladex.CreateEntity("NoName11","Femur",-47939.603436,14735.302935,-28049.685425,Reference.ObjType("Femur"))
o.Scale=1.000000
o.Orientation=0.846623,0.023899,-0.530608,0.033363



o=Bladex.CreateEntity("NoName12","Femur",-48128.648190,14705.539285,-26244.595902,Reference.ObjType("Femur"))
o.Scale=1.000000
o.Orientation=0.866556,-0.048073,-0.187513,0.460009



o=Bladex.CreateEntity("NoName0","Lampcolg",-17246.741000,-16408.548000,27789.952000,"Physic")
o.Scale=1.947745
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 5 ]
o.Lights=[ (0.000000,0.031250,(255,196,128)) ]



o=Bladex.CreateEntity("NoName0","Peanapiedra",127.847000,5943.255000,-124565.036000,"Physic")
o.Scale=10.059091
o.Orientation=0.533660,0.533660,0.463904,-0.463904



o=Bladex.CreateEntity("NoName0","Adoquinpulsador",27330.324000,3714.303000,21489.642000,"Physic")
o.Scale=4.067370
o.Orientation=0.342812,0.618450,0.342812,-0.618450



o=Bladex.CreateEntity("NoName0","ArmaduraEnanoMedia",56081.990000,4254.536000,38926.388000,"Physic")
o.Scale=1.000000
o.Orientation=0.707450,0.706729,0.005487,0.004279
o.Solid=0


o=Bladex.CreateEntity("NoName1","EsqueletoPieza1",55000.678000,4454.843000,39407.063000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.999848,0.017452,0.000000,0.000000



o=Bladex.CreateEntity("NoName2","EsqueletoPieza10",55260.447000,4448.867000,40317.852000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.416390,-0.153774,-0.057467,0.894243



o=Bladex.CreateEntity("NoName3","EsqueletoPieza10",54573.661000,4466.738000,40379.971000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.341690,0.709929,-0.322401,-0.524697



o=Bladex.CreateEntity("NoName4","EsqueletoPieza10",54692.656000,4466.623000,38874.325000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.474471,-0.041968,0.109690,-0.872401



o=Bladex.CreateEntity("NoName6","EsqueletoPieza6",55492.814000,4448.277000,40365.197000,Reference.ObjType("EsqueletoPieza6"))
o.Scale=1.000000
o.Orientation=0.095259,0.855619,0.463183,0.210481



o=Bladex.CreateEntity("NoName7","EsqueletoPieza6",58148.174000,4460.135000,39360.677000,Reference.ObjType("EsqueletoPieza6"))
o.Scale=1.000000
o.Orientation=0.872764,0.088110,0.185353,0.442903



o=Bladex.CreateEntity("NoName8","EsqueletoPieza10",58006.539000,4461.276000,40029.829000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.400257,-0.042193,0.099545,-0.910003



o=Bladex.CreateEntity("NoName9","EsqueletoPieza10",56034.703000,4698.428000,32496.069000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.740447,-0.276977,-0.506820,0.343738



o=Bladex.CreateEntity("NoName10","EsqueletoPieza10",56725.397000,4709.274000,34314.669000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.104622
o.Orientation=0.851468,-0.080593,0.463530,-0.231619



o=Bladex.CreateEntity("NoName11","Antorchaenpared",53890.635000,2932.906000,39940.802000,"Physic")
o.Scale=1.000000
o.Orientation=0.705788,0.705788,-0.043168,-0.043168
o.FiresIntensity=[ 0 ]
o.Lights=[ (5.000000,0.312500,(255,140,13)) ]



o=Bladex.CreateEntity("NoName0","Columna",-36239.588000,-2819.702000,21304.391000,"Physic")
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000



o=Bladex.CreateEntity("NoName3","Armero",-26835.194000,7164.692000,8740.926000,"Physic")
o.Scale=1.000000
o.Orientation=0.006164,0.006171,0.707080,-0.707080
Breakings.SetBreakable(o.Name,12,100)


o=Bladex.CreateEntity("NoName4","Armero",-28952.538000,7163.352000,8761.560000,"Physic")
o.Scale=1.000000
o.Orientation=0.006164,0.006171,0.707080,-0.707080
Breakings.SetBreakable(o.Name,12,100)


o=Bladex.CreateEntity("NoName5","Armero",-30021.204000,7164.599000,14718.414000,"Physic")
o.Scale=1.000000
o.Orientation=0.495618,0.495618,-0.504344,0.504344
Breakings.SetBreakable(o.Name,12,100)


o=Bladex.CreateEntity("NoName6","Armero",-30027.779000,7162.953000,16490.317000,"Physic")
o.Scale=1.000000
o.Orientation=0.495618,0.495618,-0.504344,0.504344
Breakings.SetBreakable(o.Name,12,100)


o=Bladex.CreateEntity("NoName7","Skull",-29817.853000,7896.284000,11353.917000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.885256,0.441611,0.144044,0.023528



o=Bladex.CreateEntity("NoName8","Skull",-29485.575000,7863.577000,15083.744000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.102948,-0.570865,0.110424,0.807045



o=Bladex.CreateEntity("NoName10","EsqueletoPieza6",-28668.027000,7947.981000,14843.962000,Reference.ObjType("EsqueletoPieza6"))
o.Scale=1.000000
o.Orientation=0.701480,0.109444,0.125147,0.693027



o=Bladex.CreateEntity("NoName11","EsqueletoPieza10",-29117.547000,7964.084000,14734.242000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.525701,-0.068985,0.135953,-0.836897



o=Bladex.CreateEntity("NoName12","EsqueletoPieza10",-28713.492000,7962.907000,15811.061000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.346954,0.719427,-0.408101,-0.442155



o=Bladex.CreateEntity("NoName13","EsqueletoPieza10",-26531.380000,7961.790000,14270.518000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.457988,0.587717,-0.324410,-0.582747



o=Bladex.CreateEntity("NoName14","Tabla_rota",-25894.906000,7390.184000,13601.261000,"Physic")
o.Scale=1.000000
o.Orientation=0.471312,0.439543,0.533613,0.547653
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName15","Tabla_rota",-25934.492000,7231.979000,10289.012000,"Physic")
o.Scale=1.257163
o.Orientation=0.465102,0.446109,0.540429,0.540929
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName16","Tabla_rota",-27136.999000,7943.885000,10763.543000,"Physic")
o.Scale=1.321291
o.Orientation=0.287606,0.287606,0.645974,-0.645974
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName17","Tabla_rota",-29441.570000,7163.656000,19930.047000,"Physic")
o.Scale=1.416603
o.Orientation=0.119664,0.695291,0.701147,-0.103172
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName18","EsqueletoPieza1",-28625.542000,7968.528000,19682.908000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=1.000000,0.000000,0.000000,0.000000



o=Bladex.CreateEntity("NoName19","EsqueletoPieza10",-28949.260000,7948.288000,18834.621000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.991302,0.003339,0.061537,0.116284



o=Bladex.CreateEntity("NoName20","EsqueletoPieza10",-29353.556000,7963.384000,18703.975000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.336345,0.717134,-0.314049,-0.523417



o=Bladex.CreateEntity("NoName21","EsqueletoPieza10",-27945.981000,7958.866000,18178.765000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.170975,-0.021481,0.038049,-0.984306



o=Bladex.CreateEntity("NoName22","EsqueletoPieza10",-27551.754000,7949.616000,19224.258000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.456327,0.149357,0.102374,0.871193



o=Bladex.CreateEntity("NoName0","Antorchaenpared",-25923.886000,6818.168000,11196.052000,"Physic")
o.Scale=1.000000
o.Orientation=0.030843,-0.128860,0.706434,-0.695266
o.FiresIntensity=[ 0 ]
o.Lights=[ (10.000000,0.312500,(255,128,0)) ]



o=Bladex.CreateEntity("NoName6","EsqueletoPieza10",-28943.465000,-10834.587000,10565.750000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.313671,0.758438,-0.376572,-0.429622



o=Bladex.CreateEntity("NoName7","EsqueletoPieza10",-27824.746000,-10833.661000,9765.951000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=0.741923
o.Orientation=0.471338,0.362677,-0.096133,-0.798163



o=Bladex.CreateEntity("NoName8","EsqueletoPieza1",-27335.341000,-10818.663000,9942.050000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.999848,0.017452,0.000000,0.000000



o=Bladex.CreateEntity("NoName9","Skull",-27380.701000,-10832.083000,10463.486000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.935133,0.139757,-0.321992,-0.048122



o=Bladex.CreateEntity("NoName10","EsqueletoPieza10",-27728.827000,-10836.611000,10078.733000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=0.878663
o.Orientation=0.307007,0.770230,-0.388584,-0.401865



o=Bladex.CreateEntity("NoName11","EsqueletoPieza1",-47134.749000,-10825.613000,10856.617000,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.965337,0.033710,-0.009033,0.258661



o=Bladex.CreateEntity("NoName12","Skull",-47192.550000,-10811.870000,11378.223000,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.937404,0.065550,0.023858,-0.341187



o=Bladex.CreateEntity("NoName13","EsqueletoPieza10",-45815.155000,-10835.937000,10612.649000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.347419,0.727157,-0.413876,-0.423378



o=Bladex.CreateEntity("NoName14","EsqueletoPieza10",-46284.329000,-10835.176000,10092.266000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.389389,0.663876,-0.325679,-0.549162



o=Bladex.CreateEntity("NoName15","EsqueletoPieza10",-47173.980000,-10833.881000,10013.384000,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.553404,0.226957,-0.064338,-0.798809



o=Bladex.CreateEntity("NoName16","Tabla_rota",-42762.376000,-11742.658000,9679.758000,"Physic")
o.Scale=1.549318
o.Orientation=0.482232,0.462081,0.518952,0.533500
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName17","Tabla_rota",-44526.184000,-10841.512000,10008.459000,"Physic")
o.Scale=1.000000
o.Orientation=0.627211,0.627211,0.326506,-0.326506
Sparks.SetWoodenSparkling(o.Name)


o=Bladex.CreateEntity("NoName18","TinajaPieza5",-43668.075000,-10842.545000,10529.387000,"Physic")
o.Scale=1.000000
o.Orientation=0.393749,0.670753,0.445980,0.442892



o=Bladex.CreateEntity("NoName19","TinajaPieza4",-44023.966000,-11105.039000,11701.480000,"Physic")
o.Scale=1.000000
o.Orientation=0.971356,0.097720,0.098016,-0.193162



o=Bladex.CreateEntity("NoName20","TinajaPieza4",-37519.374000,-11082.852000,10763.091000,"Physic")
o.Scale=1.000000
o.Orientation=0.948853,0.112643,-0.236850,-0.175762



o=Bladex.CreateEntity("NoName21","TinajaPieza4",-40461.410000,-11109.471000,16681.567000,"Physic")
o.Scale=1.000000
o.Orientation=0.325968,0.222490,-0.915957,0.072570



o=Bladex.CreateEntity("NoName0","EsqueletoPieza1",-47776.757412,14784.251254,-26401.209195,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.082857
o.Orientation=0.938798,0.040989,-0.341695,-0.014919



o=Bladex.CreateEntity("NoName1","EsqueletoPieza10",-46309.170203,14937.027483,-25653.086899,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.354936,0.764822,-0.348635,-0.409294



o=Bladex.CreateEntity("NoName2","Skull",-43442.057424,15422.633127,-27100.464750,Reference.ObjType("Skull"))
o.Scale=1.295256
o.Orientation=0.869996,0.476702,-0.022890,0.123852



o=Bladex.CreateEntity("NoName3","Skull",-38466.645559,18167.797141,-42787.100513,Reference.ObjType("Skull"))
o.Scale=1.126825
o.Orientation=0.577779,0.371832,0.310786,0.656753



o=Bladex.CreateEntity("NoName4","Skull",-36531.016095,18178.318951,-42846.913655,Reference.ObjType("Skull"))
o.Scale=1.149474
o.Orientation=0.769016,0.499603,-0.355086,0.181455



o=Bladex.CreateEntity("NoName5","EsqueletoPieza10",-37161.882123,18347.844392,-44241.259620,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.342683,0.410066,0.157033,0.830515



o=Bladex.CreateEntity("NoName6","EsqueletoPieza1",-36675.491711,18290.431832,-43340.451024,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.093685
o.Orientation=0.997564,0.069756,0.000000,0.000000



o=Bladex.CreateEntity("NoName7","EsqueletoPieza1",-37700.573887,19773.584584,-59948.644004,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.082857
o.Orientation=0.986286,-0.165048,0.000000,0.000000



o=Bladex.CreateEntity("NoName8","Skull",-37704.899516,19977.173564,-59398.855343,Reference.ObjType("Skull"))
o.Scale=1.000000
o.Orientation=0.970296,-0.000000,-0.000000,-0.241922



o=Bladex.CreateEntity("NoName9","EsqueletoPieza10",-37942.469252,19748.375940,-60407.580816,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.209362,-0.567412,0.191053,-0.773117



o=Bladex.CreateEntity("NoName10","EsqueletoPieza10",-38113.815804,19662.062434,-60654.361161,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.733874,0.026951,0.300484,0.608615



o=Bladex.CreateEntity("NoName11","EsqueletoPieza10",-37939.019784,19450.326445,-61815.990771,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.424781,0.076509,0.051050,0.900612



o=Bladex.CreateEntity("NoName12","EsqueletoPieza10",-38420.048480,19446.704063,-62050.744046,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.327810,-0.312418,-0.099983,0.885968



o=Bladex.CreateEntity("NoName13","EsqueletoPieza1",-37483.731210,19391.052244,-63363.276094,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.104622
o.Orientation=0.999017,0.042020,0.006551,-0.012540



o=Bladex.CreateEntity("NoName14","Adoquinpulsador",-62027.263062,15237.772111,-19507.364993,"Physic")
o.Scale=4.232522
o.Orientation=0.697409,0.697409,0.116706,-0.116706



o=Bladex.CreateEntity("NoName3","EsqueletoPieza1",94892.165703,2600.250721,-15009.162843,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.027202,-0.997515,-0.010168,-0.064188


o=Bladex.CreateEntity("NoName5","EsqueletoPieza10",94353.728973,2713.827703,-14892.083351,Reference.ObjType("EsqueletoPieza10"))
o.Scale=1.000000
o.Orientation=0.404611,-0.184163,0.159570,-0.881425


o=Bladex.CreateEntity("NoName6","EsqueletoPieza1",95536.245508,2619.284062,-15709.889442,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.605917,0.098468,-0.789197,-0.018343


o=Bladex.CreateEntity("NoName9","EsqueletoPieza2",95361.824333,2651.632592,-15202.178192,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.893370,0.410162,-0.001600,0.183451


o=Bladex.CreateEntity("NoName11","EsqueletoPieza2",94723.724707,2650.780579,-15439.913070,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.893319,0.433923,-0.099984,-0.060786


o=Bladex.CreateEntity("NoName12","EsqueletoPieza2",94840.493702,2651.544982,-15929.180803,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.294742,-0.558289,-0.664810,0.399335


o=Bladex.CreateEntity("NoName13","EsqueletoPieza2",94389.302496,2640.876001,-15248.268035,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.625178,0.098540,0.184771,0.751866


o=Bladex.CreateEntity("NoName16","EsqueletoPieza2",-12603.729650,7904.114049,11179.298783,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.149621,0.631231,-0.759390,-0.049877


o=Bladex.CreateEntity("NoName17","EsqueletoPieza2",-12801.836845,7900.150826,10566.697406,Reference.ObjType("EsqueletoPieza2"))
o.Scale=1.000000
o.Orientation=0.330371,0.570925,0.729275,0.181816


o=Bladex.CreateEntity("NoName19","EsqueletoPieza1",-13049.959818,7871.298848,11229.708655,Reference.ObjType("EsqueletoPieza1"))
o.Scale=1.000000
o.Orientation=0.998491,0.046528,-0.006734,-0.028391


o=Bladex.CreateEntity("NoName0","Reja",-31118.957445,7267.963372,9702.813846)
o.Scale=1.361327
o.Orientation=0.707080,-0.006171,0.006171,-0.707080


o=Bladex.CreateEntity("NoName1","Reja",-31240.574877,7293.692784,12749.862654)
o.Scale=1.361327
o.Orientation=0.707080,-0.006171,-0.006171,-0.707080


o=Bladex.CreateEntity("NoName2","Reja",-31162.966007,7387.998977,18701.262291)
o.Scale=1.374941
o.Orientation=0.706999,-0.012341,0.012341,-0.706999
