# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 12 Items.

o=Bladex.CreateEntity("NoName0","Farol2",12852.154000,-6486.825000,-2331.033000)
o.Static=1
o.Scale=1.711410
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 11 ]
o.Lights=[ (30.000000,0.160000,(240,126,0)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Roca1",-416.657000,-1.417000,-11377.889000)
o.Static=1
o.Scale=2.522829
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Roca2",3349.078000,-1530.633000,-10301.360000)
o.Static=1
o.Scale=2.928926
o.Orientation=0.342020,0.939693,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","Arbolseco2",20656.976000,-3515.646000,-19543.660000)
o.Static=1
o.Scale=1.677689
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Arbolseco",2171.030000,-4027.633000,-16613.231000)
o.Static=1
o.Scale=2.047099
o.Orientation=0.707107,0.707107,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Roca1Aurelio",28498.767000,176.121000,-13348.260000)
o.Static=1
o.Scale=3.235356
o.Orientation=0.970296,-0.241922,0.000000,0.000000
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Antorchaenpared",-3778.233000,-8985.495000,6077.262000)
o.Static=1
o.Scale=1.000000
o.Orientation=0.707107,0.707107,0.000000,0.000000
o.FiresIntensity=[ 0 ]
o.Lights=[ (16.000000,0.031250,(255,145,23)) ]
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Viga",3810.206000,-8074.499000,6877.941000)
o.Static=1
o.Scale=2.899927
o.Orientation=0.504344,0.504344,-0.495618,0.495618
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName0","Roca1Aurelio",7324.757000,-318.291000,-26474.662000)
o.Static=1
o.Scale=2.678034
o.Orientation=0.563107,0.365172,0.576830,-0.465647
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName1","Roca1Aurelio",3051.729000,-1481.913000,-29691.012000)
o.Static=1
o.Scale=3.573846
o.Orientation=0.009183,0.906378,-0.105887,0.408880
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName2","Roca1Aurelio",50736.906000,8079.490000,-15971.471000)
o.Static=1
o.Scale=3.366725
o.Orientation=0.106774,-0.075218,0.058766,0.989691
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


o=Bladex.CreateEntity("NoName3","GanchoAurelio",12908.026000,-6913.996000,-2876.461000)
o.Static=1
o.Scale=2.899927
o.Orientation=0.508650,0.508650,0.491198,-0.491198
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


